package com.ecoedu.Vistas.Consultas;



import com.ecoedu.model.Detalle_Medicamentos;
import java.awt.Color;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */
public class Consultas extends javax.swing.JPanel {  
    EntityManager jpa;
    public Consultas(EntityManager objJPA) {
        initComponents();
        this.jpa=objJPA;
        //principalEjecucion();
        //ConsultaBD();    
        //llenarTabla(lista_Detalles_control_paciente);
   
    }
    public void ConsultaBD(){
        Query query1=jpa.createQuery("SELECT p FROM Detalle_control_paciente p");
        //lista_Detalles_control_paciente=query1.getResultList();
        
    }
    public void principalEjecucion(){
        jcbYearDesde.setVisible(false);
        jlblDesde.setVisible(false);
        jlblHasta.setVisible(false);
        jcbYearHasta.setVisible(false);
        jcbMeses.setVisible(false);
        jcbYear.setVisible(false);
        jlblMes.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        head2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jrbEspecifica1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jrbMesayo1 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jlblDesde = new javax.swing.JLabel();
        jcbYearDesde = new rojeru_san.componentes.RSDateChooser();
        jlblHasta = new javax.swing.JLabel();
        jcbYearHasta = new rojeru_san.componentes.RSDateChooser();
        jlblMes = new javax.swing.JLabel();
        jcbMeses = new javax.swing.JComboBox<>();
        jcbYear = new rojeru_san.componentes.RSYearDate();
        body2 = new javax.swing.JPanel();
        cuerpo1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVentas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(207, 48, 72));
        head.setPreferredSize(new java.awt.Dimension(100, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CONSULTAS");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        head2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(890, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(880, 30));
        jPanel4.setRequestFocusEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BÚSQUEDA ESPECÍFICA");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setPreferredSize(new java.awt.Dimension(162, 30));
        jPanel4.add(jLabel16);

        jrbEspecifica1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbEspecifica1);
        jrbEspecifica1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrbEspecifica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbEspecifica1.setPreferredSize(new java.awt.Dimension(15, 30));
        jrbEspecifica1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbEspecifica1MouseClicked(evt);
            }
        });
        jPanel4.add(jrbEspecifica1);

        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel2);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("BÚSQUEDA POR MES Y/O AÑO");
        jLabel19.setPreferredSize(new java.awt.Dimension(210, 30));
        jPanel4.add(jLabel19);

        jrbMesayo1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbMesayo1);
        jrbMesayo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbMesayo1.setPreferredSize(new java.awt.Dimension(15, 30));
        jrbMesayo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbMesayo1MouseClicked(evt);
            }
        });
        jPanel4.add(jrbMesayo1);

        jPanel7.add(jPanel4);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(880, 40));

        jlblDesde.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblDesde.setText("Desde :");
        jPanel11.add(jlblDesde);

        jcbYearDesde.setFormatoFecha("dd/MM/yyyy ");
        jcbYearDesde.setPlaceholder("Desde ");
        jcbYearDesde.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel11.add(jcbYearDesde);

        jlblHasta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblHasta.setText("Hasta :");
        jPanel11.add(jlblHasta);

        jcbYearHasta.setFormatoFecha("dd/MM/yyyy\n");
        jcbYearHasta.setPlaceholder("Hasta");
        jcbYearHasta.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel11.add(jcbYearHasta);

        jlblMes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblMes.setText("Mes :");
        jPanel11.add(jlblMes);

        jcbMeses.setBackground(new java.awt.Color(0, 112, 192));
        jcbMeses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbMeses.setForeground(new java.awt.Color(67, 150, 209));
        jcbMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbMeses.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(jcbMeses);

        jcbYear.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel11.add(jcbYear);

        jPanel7.add(jPanel11);

        head2.add(jPanel7);

        body.add(head2, java.awt.BorderLayout.PAGE_START);

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.setMaximumSize(new java.awt.Dimension(1990, 650));
        body2.setMinimumSize(new java.awt.Dimension(200, 200));
        body2.setPreferredSize(new java.awt.Dimension(9900, 520));
        body2.setLayout(new java.awt.BorderLayout());

        cuerpo1.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo1.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(900, 290));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jtblVentas.setBorder(new javax.swing.border.MatteBorder(null));
        jtblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto", "Monto Total", "Q. F."
            }
        ));
        jtblVentas.setGridColor(new java.awt.Color(0, 0, 0));
        jtblVentas.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblVentas.setPreferredSize(new java.awt.Dimension(200, 260));
        jtblVentas.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jtblVentas);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tabla de Registro de Medicamentos Entregados");
        jPanel9.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jLabel14.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jLabel18.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel18, java.awt.BorderLayout.LINE_START);

        cuerpo1.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(900, 40));

        jLabel4.setText("Pie");
        jLabel4.setMaximumSize(new java.awt.Dimension(500, 0));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(420, 30));
        jPanel10.add(jLabel4);

        cuerpo1.add(jPanel10);

        body2.add(cuerpo1, java.awt.BorderLayout.CENTER);

        body.add(body2, java.awt.BorderLayout.CENTER);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbEspecifica1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbEspecifica1MouseClicked
        jcbMeses.setVisible(false);
        jcbYear.setVisible(false);
        jlblMes.setVisible(false);

        jcbYearDesde.setVisible(true);
        jlblDesde.setVisible(true);
        jlblHasta.setVisible(true);
        jcbYearHasta.setVisible(true);
    }//GEN-LAST:event_jrbEspecifica1MouseClicked

    private void jrbMesayo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbMesayo1MouseClicked
        jcbYearDesde.setVisible(false);
        jlblDesde.setVisible(false);
        jlblHasta.setVisible(false);
        jcbYearHasta.setVisible(false);

        jcbMeses.setVisible(true);
        jcbYear.setVisible(true);
        jlblMes.setVisible(true);
    }//GEN-LAST:event_jrbMesayo1MouseClicked

    public void llenarTabla(List<Detalle_Medicamentos> listaDetalleControl){ 
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Fecha","Producto Farmacéutico","Cantidad","Precio Unidad","Código Estudiante","Química(o) Farmacéutica(o)"};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false, false, false
                         };
                 @Override
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < listaDetalleControl.size(); i++){
                 System.out.println("entro");
                 fila_actividad[0]=listaDetalleControl.get(i).getFecha();
                 fila_actividad[1]=listaDetalleControl.get(i).getId_Medicamento().getNombre();             
                 fila_actividad[2]=listaDetalleControl.get(i).getCantidad();  
                 fila_actividad[3]=listaDetalleControl.get(i).getPrecio_Unitario();   
                // fila_actividad[4]=listaDetalleControl.get(i).getControl_Paciente().getPersona().getCodigo();   
                 fila_actividad[5]=listaDetalleControl.get(i).getUsuario().getPersona().getInfoPersona();  
                 modelo.addRow(fila_actividad);//agregando filas
                 }
            jtblVentas.setModel(modelo); 
            jtblVentas.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblVentas.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(5).setCellRenderer(tcr);
            
            jtblVentas.getColumnModel().getColumn(5).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(4).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(3).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(2).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(1).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtblVentas.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblVentas.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblVentas.getTableHeader().setBackground(Color.BLUE);
            jtblVentas.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblVentas.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblVentas.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblVentas.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtblVentas.getColumnModel().getColumn(3).setPreferredWidth(125);
            jtblVentas.getColumnModel().getColumn(4).setPreferredWidth(90);
            jtblVentas.getColumnModel().getColumn(5).setPreferredWidth(220);
            
            ((DefaultTableCellRenderer)jtblVentas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64
            

    
           
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel body2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cuerpo1;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbMeses;
    private rojeru_san.componentes.RSYearDate jcbYear;
    private rojeru_san.componentes.RSDateChooser jcbYearDesde;
    private rojeru_san.componentes.RSDateChooser jcbYearHasta;
    private javax.swing.JLabel jlblDesde;
    private javax.swing.JLabel jlblHasta;
    private javax.swing.JLabel jlblMes;
    private javax.swing.JRadioButton jrbEspecifica1;
    private javax.swing.JRadioButton jrbMesayo1;
    private javax.swing.JTable jtblVentas;
    // End of variables declaration//GEN-END:variables

    
    
    
    

}
