package com.ecoedu.Vistas.Inventario;




import com.ecoedu.Vistas.Herramienta;
import com.ecoedu.Vistas.vista_base.Principal;
import com.ecoedu.model.Lote_detalle;
import com.ecoedu.model.RegistroMensualLotes;
import com.ecoedu.model.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */
public class Abrir_Inventario extends javax.swing.JPanel {  
    List<Lote_detalle> Lista_lote_detalle;
    Principal objPrincipal;
    Usuario objUsuario;
    EntityManager jpa;
    public Abrir_Inventario(EntityManager jpa2,Principal OBJPrincipal,Usuario objUser ){
        initComponents();   
        this.objUsuario=objUser;
        this.jpa=jpa2;
        this.objPrincipal=OBJPrincipal;             
    }
    public void ConsultaBD(){             
         if(jpa.createQuery("SELECT p FROM RegistroMensualLotes p where fecha_cierre is null").getResultList().isEmpty()){
             jlblAdvertencia.setText("");
             Lista_lote_detalle=jpa.createQuery("SELECT p FROM Lote_detalle p").getResultList();
             Collections.sort(Lista_lote_detalle);//ordenando A-Z (método como Override)
             llenarTabla(Lista_lote_detalle);
             jbtnAbrirInventario.setEnabled(true);
             }
         else{
             jlblAdvertencia.setText("El Inventario Mensual Está Abierto");
             jbtnAbrirInventario.setEnabled(false);
             Lista_lote_detalle=new ArrayList<>();
             llenarTabla(Lista_lote_detalle);
             }
         }
    
    public void principalEjecucion(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        head2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlblAdvertencia = new javax.swing.JLabel();
        body2 = new javax.swing.JPanel();
        cuerpo1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVentas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jbtnAbrirInventario = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(207, 48, 72));
        head.setPreferredSize(new java.awt.Dimension(100, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ABRIR INVENTARIO MENSUAL");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        head2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(890, 50));

        jlblAdvertencia.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jlblAdvertencia.setForeground(new java.awt.Color(0, 0, 255));
        jlblAdvertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAdvertencia.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanel7.add(jlblAdvertencia);

        head2.add(jPanel7);

        body.add(head2, java.awt.BorderLayout.PAGE_START);

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.setMaximumSize(new java.awt.Dimension(1990, 650));
        body2.setMinimumSize(new java.awt.Dimension(200, 200));
        body2.setPreferredSize(new java.awt.Dimension(9900, 520));
        body2.setLayout(new java.awt.BorderLayout());

        cuerpo1.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo1.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(900, 330));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jtblVentas.setBorder(new javax.swing.border.MatteBorder(null));
        jtblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto", "Monto Total", "Q. F."
            }
        ));
        jtblVentas.setGridColor(new java.awt.Color(0, 0, 0));
        jtblVentas.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblVentas.setPreferredSize(new java.awt.Dimension(200, 390));
        jtblVentas.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jtblVentas);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setPreferredSize(new java.awt.Dimension(0, 14));
        jPanel9.add(jLabel11, java.awt.BorderLayout.PAGE_END);
        jLabel11.getAccessibleContext().setAccessibleName("");

        jLabel14.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jLabel18.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel18, java.awt.BorderLayout.LINE_START);

        cuerpo1.add(jPanel9);

        jbtnAbrirInventario.setBackground(new java.awt.Color(0, 0, 0));
        jbtnAbrirInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnAbrirInventario.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAbrirInventario.setText("ABRIR INVENTARIO MENSUAL");
        jbtnAbrirInventario.setPreferredSize(new java.awt.Dimension(220, 25));
        jbtnAbrirInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAbrirInventarioActionPerformed(evt);
            }
        });
        cuerpo1.add(jbtnAbrirInventario);

        body2.add(cuerpo1, java.awt.BorderLayout.CENTER);

        body.add(body2, java.awt.BorderLayout.CENTER);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAbrirInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAbrirInventarioActionPerformed

        Date fechaApertu=new Date();
        Date fechaApertuReal=new Date();
        fechaApertuReal.setDate(1);
        fechaApertuReal.setHours(0);
        fechaApertuReal.setMinutes(0);
        fechaApertuReal.setSeconds(0);
        jpa.getTransaction().begin();
        for (Lote_detalle lote_detalle : Lista_lote_detalle){
            jpa.persist(new RegistroMensualLotes(lote_detalle.getCantidad(), fechaApertuReal, fechaApertu, objUsuario, lote_detalle));
            }
        ConsultaBD();
        principalEjecucion();
        JOptionPane.showMessageDialog(jlblAdvertencia, "Aperturó con exito el mes"+(fechaApertuReal.getMonth()+1));
        jpa.getTransaction().commit();
        
    }//GEN-LAST:event_jbtnAbrirInventarioActionPerformed

    public void llenarTabla(List<Lote_detalle> lista_lote_detalle){ 
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Código","Producto Farmacéutico","Cant","P.V.R","Código Factura","Laboratorio","F.V"};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false, false, false,false
                         };
                 @Override
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (Lote_detalle objLote : Lista_lote_detalle){
                 fila_actividad[0]=objLote.getCodigo();
                 fila_actividad[1]=objLote.getInventario().getMedicamento().getNombre();
                 fila_actividad[2]=objLote.getCantidad();
                 fila_actividad[3]=objLote.getPrecio_Venta_Redondeado();  
                 fila_actividad[4]=objLote.getFactura().getCodigo_factura();   
                 fila_actividad[5]=objLote.getRolFabricante().getNombre_rol();   
                 fila_actividad[6]=Herramienta.formatoFecha(objLote.getFecha_vencimiento());  
                 modelo.addRow(fila_actividad);//agregando filas
                 }
            jtblVentas.setModel(modelo); 
            jtblVentas.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblVentas.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(5).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(6).setCellRenderer(tcr);
            
            jtblVentas.setFont(new java.awt.Font("Tahoma", 0, 13));
            jtblVentas.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18));
            jtblVentas.getTableHeader().setBackground(Color.BLUE);
            jtblVentas.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblVentas.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblVentas.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblVentas.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtblVentas.getColumnModel().getColumn(3).setPreferredWidth(125);
            jtblVentas.getColumnModel().getColumn(4).setPreferredWidth(130);
            jtblVentas.getColumnModel().getColumn(5).setPreferredWidth(180);
            jtblVentas.getColumnModel().getColumn(6).setPreferredWidth(120);
            
            ((DefaultTableCellRenderer)jtblVentas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64
            

    
           
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel body2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cuerpo1;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAbrirInventario;
    private javax.swing.JLabel jlblAdvertencia;
    private javax.swing.JTable jtblVentas;
    // End of variables declaration//GEN-END:variables

}
