package com.ecoedu.Vistas.Inventario;


import com.ecoedu.model.Detalle_Medicamentos;
import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */
public class AgregarMedicamentos extends javax.swing.JPanel {   
    public AgregarMedicamentos() {
        initComponents();
        jcbYearDesde.setVisible(false);
        jlblDesde.setVisible(false);
        jlblHasta.setVisible(false);
        jcbYearHasta.setVisible(false);
        jcbMeses.setVisible(false);
        jcbYear.setVisible(false);
        jlblMes.setVisible(false);
        
        
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        JpanelBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jrbEspecifica = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jrbMesayo = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jlblDesde = new javax.swing.JLabel();
        jcbYearDesde = new rojeru_san.componentes.RSDateChooser();
        jlblHasta = new javax.swing.JLabel();
        jcbYearHasta = new rojeru_san.componentes.RSDateChooser();
        jlblMes = new javax.swing.JLabel();
        jcbMeses = new javax.swing.JComboBox<>();
        jcbYear = new rojeru_san.componentes.RSYearDate();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(100, 0, 7));
        head.setPreferredSize(new java.awt.Dimension(100, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("AGREGAR NUEVOS MEDICAMENTOS");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        JpanelBody.setBackground(new java.awt.Color(255, 255, 255));
        JpanelBody.setMaximumSize(new java.awt.Dimension(9909, 6500));
        JpanelBody.setMinimumSize(new java.awt.Dimension(990, 650));
        JpanelBody.setPreferredSize(new java.awt.Dimension(900, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 30));
        jPanel1.setRequestFocusEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("BÚSQUEDA ESPECÍFICA");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setPreferredSize(new java.awt.Dimension(162, 30));
        jPanel1.add(jLabel13);

        jrbEspecifica.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbEspecifica);
        jrbEspecifica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrbEspecifica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbEspecifica.setPreferredSize(new java.awt.Dimension(15, 30));
        jrbEspecifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbEspecificaMouseClicked(evt);
            }
        });
        jPanel1.add(jrbEspecifica);

        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel1);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("BÚSQUEDA POR MES Y/O AÑO");
        jLabel17.setPreferredSize(new java.awt.Dimension(210, 30));
        jPanel1.add(jLabel17);

        jrbMesayo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbMesayo);
        jrbMesayo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbMesayo.setPreferredSize(new java.awt.Dimension(15, 30));
        jrbMesayo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbMesayoMouseClicked(evt);
            }
        });
        jPanel1.add(jrbMesayo);

        JpanelBody.add(jPanel1);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(900, 40));

        jlblDesde.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblDesde.setText("Desde :");
        jPanel8.add(jlblDesde);

        jcbYearDesde.setFormatoFecha("dd/MM/yyyy ");
        jcbYearDesde.setPlaceholder("Desde ");
        jcbYearDesde.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel8.add(jcbYearDesde);

        jlblHasta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblHasta.setText("Hasta :");
        jPanel8.add(jlblHasta);

        jcbYearHasta.setFormatoFecha("dd/MM/yyyy\n");
        jcbYearHasta.setPlaceholder("Hasta");
        jcbYearHasta.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel8.add(jcbYearHasta);

        jlblMes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblMes.setText("Mes :");
        jPanel8.add(jlblMes);

        jcbMeses.setBackground(new java.awt.Color(0, 112, 192));
        jcbMeses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbMeses.setForeground(new java.awt.Color(67, 150, 209));
        jcbMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbMeses.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel8.add(jcbMeses);

        jcbYear.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel8.add(jcbYear);

        JpanelBody.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(880, 350));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto", "Monto Total", "Q. F."
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setMinimumSize(new java.awt.Dimension(500, 100));
        jTable1.setPreferredSize(new java.awt.Dimension(800, 600));
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tabla de Registro de Medicamentos desde 28/04/2019 hasta 29/06/2020");
        jLabel11.setPreferredSize(new java.awt.Dimension(900, 14));
        jPanel9.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        JpanelBody.add(jPanel9);

        add(JpanelBody, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbEspecificaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbEspecificaMouseClicked
        jcbMeses.setVisible(false);
        jcbYear.setVisible(false);
        jlblMes.setVisible(false);
        
        jcbYearDesde.setVisible(true);
        jlblDesde.setVisible(true);
        jlblHasta.setVisible(true);
        jcbYearHasta.setVisible(true);
    }//GEN-LAST:event_jrbEspecificaMouseClicked

    private void jrbMesayoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbMesayoMouseClicked
        jcbYearDesde.setVisible(false);
        jlblDesde.setVisible(false);
        jlblHasta.setVisible(false);
        jcbYearHasta.setVisible(false);
        
        jcbMeses.setVisible(true);
        jcbYear.setVisible(true);
        jlblMes.setVisible(true);
        
       
    }//GEN-LAST:event_jrbMesayoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelBody;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel head;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbMeses;
    private rojeru_san.componentes.RSYearDate jcbYear;
    private rojeru_san.componentes.RSDateChooser jcbYearDesde;
    private rojeru_san.componentes.RSDateChooser jcbYearHasta;
    private javax.swing.JLabel jlblDesde;
    private javax.swing.JLabel jlblHasta;
    private javax.swing.JLabel jlblMes;
    private javax.swing.JRadioButton jrbEspecifica;
    private javax.swing.JRadioButton jrbMesayo;
    // End of variables declaration//GEN-END:variables
public void llenarTabla(List<Detalle_Medicamentos> listaDetalleControl){
    System.out.println("ols");
        DefaultTableModel modelo;
        Object[] fila_actividad = null;
             //.....................................TABLA......................................
             String [] lista={"Fecha","Producto Farmacéutico","Cantidad","Precio Unidad","Precio Total","Química(o) Farmacéutica(o)"}; 
             boolean[] canEdit = new boolean [] {false, false, false, false, false,false};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false, false, false
                         };
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < listaDetalleControl.size(); i++){
                 fila_actividad[0]=listaDetalleControl.get(i).getFecha();
                 fila_actividad[1]=listaDetalleControl.get(i).getId_Medicamento().getNombre();             
                 fila_actividad[2]=listaDetalleControl.get(i).getCantidad();  
                 fila_actividad[3]=listaDetalleControl.get(i).getPrecio_Unitario();   
                 fila_actividad[4]=listaDetalleControl.get(i).getPrecio_Total();   
                 fila_actividad[5]=listaDetalleControl.get(i).getUsuario().getPersona().getInfoPersona();  
                 modelo.addRow(fila_actividad);//agregando filas
                 }
            jTable1.setModel(modelo); 
            jTable1.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jTable1.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jTable1.getColumnModel().getColumn(5).setCellRenderer(tcr);
            
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable1.setFont(new java.awt.Font("Tahoma", 0, 15));
            jTable1.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jTable1.getTableHeader().setBackground(Color.BLUE);
            jTable1.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(154);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(125);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(220);
            
            ((DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64
            

    
           
    }
    
    
    

}
