package com.ecoedu.Vistas.Inventario;
import com.ecoedu.Vistas.Herramienta;
import com.ecoedu.Vistas.vista_base.Principal;
import com.ecoedu.model.Detalle_Medicamentos;
import com.ecoedu.model.RegistroMensualLotes;
import com.ecoedu.model.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */
public class Cerrar_Inventario extends javax.swing.JPanel{  
    List<RegistroMensualLotes> Lista_Registro_Mensual;
    Principal objPrincipal;
    Usuario objUsuario;
    EntityManager jpa;
    boolean estadoCierre=false;
    public Cerrar_Inventario(EntityManager jpa2,Principal OBJPrincipal,Usuario objUser ){
        initComponents();   
        this.objUsuario=objUser;
        this.jpa=jpa2;
        this.objPrincipal=OBJPrincipal;             
    }
    public void ConsultaBD(){   
        Lista_Registro_Mensual=jpa.createQuery("SELECT p FROM RegistroMensualLotes p where fecha_cierre_real is null").getResultList();
        if(!Lista_Registro_Mensual.isEmpty()){
             jlblAdvertencia.setText("");
             Collections.sort(Lista_Registro_Mensual);//ordenando A-Z (método como Override)
             llenarTabla(Lista_Registro_Mensual); 
             if(Lista_Registro_Mensual.get(0).getFecha_cierra()==null){
                 jlblAdvertencia.setText("Cierre del inventario de "+Herramienta.getNombreMes(Lista_Registro_Mensual.get(0).getFecha_apertura().getMonth()+1));
                 jlblAdverte.setText("Click en el Lote");
                 jbtnCerrarInventario.setEnabled(true);
                 }
             else{
                 jlblAdvertencia.setText("Inventaríe los lotes de la Lista, correspondientes al mes de "+Herramienta.getNombreMes(Lista_Registro_Mensual.get(0).getFecha_apertura().getMonth()+1));
                 }
             
             if(Lista_Registro_Mensual.get(0).getFecha_apertura().getMonth()==new Date().getMonth()){
                jbtnCerrarInventario.setText("CERRAR EL INVENTARIO ANTES QUE TERMINE EL MES"); 
             }
             else{
                jbtnCerrarInventario.setText("CERRAR EL INVENTARIO"); 
             }
             jbtnGuardarCierreLote.setVisible(!(Lista_Registro_Mensual.get(0).getFecha_cierra()==null));
             jbtnCerrarInventario.setVisible(Lista_Registro_Mensual.get(0).getFecha_cierra()==null);
             jbtnDescruzar.setVisible(!(Lista_Registro_Mensual.get(0).getFecha_cierra()==null));
             }
         else{
             jlblAdvertencia.setText("El Inventario Está Cerrado");  
             jbtnCerrarInventario.setEnabled(false);
             jlblAdverte.setText("");
             Lista_Registro_Mensual=new ArrayList<>();
             llenarTabla(Lista_Registro_Mensual);
             }
         }
    
    public void principalEjecucion(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        head2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlblAdvertencia = new javax.swing.JLabel();
        body2 = new javax.swing.JPanel();
        vistaRegistroLotes = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblVentas = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlblAdverte = new javax.swing.JLabel();
        jbtnCerrarInventario = new javax.swing.JButton();
        jbtnDescruzarGeneral = new javax.swing.JButton();
        vistaLoteAcerrar = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblDetalleMedicamento = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jlblFechaVen = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jlblPF = new javax.swing.JLabel();
        jlblFF = new javax.swing.JLabel();
        jlblConc = new javax.swing.JLabel();
        jlblCodigoLote = new javax.swing.JLabel();
        jlblCantInicial = new javax.swing.JLabel();
        jbtnDescruzar = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jlblCantFinal = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jlblFechaAperturada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnAbrirInventario3 = new javax.swing.JButton();
        jbtnGuardarCierreLote = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(207, 48, 72));
        head.setPreferredSize(new java.awt.Dimension(100, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CERRAR INVENTARIO MENSUAL");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        head2.setBackground(new java.awt.Color(255, 255, 255));
        head2.setPreferredSize(new java.awt.Dimension(900, 56));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(890, 50));

        jlblAdvertencia.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jlblAdvertencia.setForeground(new java.awt.Color(0, 0, 255));
        jlblAdvertencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAdvertencia.setPreferredSize(new java.awt.Dimension(888, 40));
        jPanel7.add(jlblAdvertencia);

        head2.add(jPanel7);

        body.add(head2, java.awt.BorderLayout.PAGE_START);

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.setMaximumSize(new java.awt.Dimension(1990, 650));
        body2.setMinimumSize(new java.awt.Dimension(200, 200));
        body2.setPreferredSize(new java.awt.Dimension(9900, 520));
        body2.setLayout(new java.awt.CardLayout());

        vistaRegistroLotes.setBackground(new java.awt.Color(255, 255, 255));
        vistaRegistroLotes.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(900, 380));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jtblVentas.setBorder(new javax.swing.border.MatteBorder(null));
        jtblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto", "Monto Total", "Q. F."
            }
        ));
        jtblVentas.setGridColor(new java.awt.Color(0, 0, 0));
        jtblVentas.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblVentas.setPreferredSize(new java.awt.Dimension(200, 390));
        jtblVentas.setRequestFocusEnabled(false);
        jtblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblVentas);
        if (jtblVentas.getColumnModel().getColumnCount() > 0) {
            jtblVentas.getColumnModel().getColumn(3).setHeaderValue("Monto");
            jtblVentas.getColumnModel().getColumn(4).setHeaderValue("Monto Total");
            jtblVentas.getColumnModel().getColumn(5).setHeaderValue("Q. F.");
        }

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel14.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jLabel18.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel18, java.awt.BorderLayout.LINE_START);

        jlblAdverte.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jlblAdverte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAdverte.setText("Click en el Lote a Cerrar");
        jlblAdverte.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanel9.add(jlblAdverte, java.awt.BorderLayout.PAGE_END);

        vistaRegistroLotes.add(jPanel9);

        jbtnCerrarInventario.setBackground(new java.awt.Color(0, 0, 0));
        jbtnCerrarInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnCerrarInventario.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCerrarInventario.setText("error");
        jbtnCerrarInventario.setPreferredSize(new java.awt.Dimension(400, 25));
        jbtnCerrarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarInventarioActionPerformed(evt);
            }
        });
        vistaRegistroLotes.add(jbtnCerrarInventario);

        jbtnDescruzarGeneral.setBackground(new java.awt.Color(255, 0, 0));
        jbtnDescruzarGeneral.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnDescruzarGeneral.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDescruzarGeneral.setText("DESCRUZAR");
        jbtnDescruzarGeneral.setPreferredSize(new java.awt.Dimension(220, 25));
        jbtnDescruzarGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDescruzarGeneralActionPerformed(evt);
            }
        });
        vistaRegistroLotes.add(jbtnDescruzarGeneral);

        body2.add(vistaRegistroLotes, "card2");

        vistaLoteAcerrar.setBackground(new java.awt.Color(255, 255, 255));
        vistaLoteAcerrar.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(900, 395));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblDetalleMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtblDetalleMedicamento);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 900, 170));

        jLabel37.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel37.setText("Cantidad Inicial:");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jlblFechaVen.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblFechaVen.setForeground(new java.awt.Color(0, 0, 255));
        jlblFechaVen.setText("error");
        jPanel10.add(jlblFechaVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel39.setText("F.F:");
        jPanel10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel40.setText("Conc:");
        jPanel10.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel41.setText("Código Lote:");
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel42.setText("Lista de Transacciones del Mes del P.F ");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel43.setText("Fecha Aperturada:");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel44.setText("Nombre Medicamento:");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jlblPF.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblPF.setForeground(new java.awt.Color(0, 0, 255));
        jlblPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPF.setText("error");
        jPanel10.add(jlblPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 650, -1));

        jlblFF.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblFF.setForeground(new java.awt.Color(0, 0, 255));
        jlblFF.setText("sd");
        jPanel10.add(jlblFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jlblConc.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblConc.setForeground(new java.awt.Color(0, 0, 255));
        jlblConc.setText("error");
        jPanel10.add(jlblConc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jlblCodigoLote.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblCodigoLote.setForeground(new java.awt.Color(0, 0, 255));
        jlblCodigoLote.setText("error");
        jPanel10.add(jlblCodigoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        jlblCantInicial.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblCantInicial.setForeground(new java.awt.Color(0, 0, 255));
        jlblCantInicial.setText("error");
        jPanel10.add(jlblCantInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        jbtnDescruzar.setBackground(new java.awt.Color(255, 0, 0));
        jbtnDescruzar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnDescruzar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDescruzar.setText("DESCRUZAR");
        jbtnDescruzar.setPreferredSize(new java.awt.Dimension(220, 25));
        jbtnDescruzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDescruzarActionPerformed(evt);
            }
        });
        jPanel10.add(jbtnDescruzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel38.setText("Cantidad Final:");
        jPanel10.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        jlblCantFinal.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblCantFinal.setForeground(new java.awt.Color(0, 0, 255));
        jlblCantFinal.setText("error");
        jPanel10.add(jlblCantFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel45.setText("Fecha Ven:");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jlblFechaAperturada.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 22)); // NOI18N
        jlblFechaAperturada.setForeground(new java.awt.Color(0, 0, 255));
        jlblFechaAperturada.setText("error");
        jlblFechaAperturada.setPreferredSize(new java.awt.Dimension(45, 344));
        jPanel10.add(jlblFechaAperturada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, 25));

        jLabel4.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel4.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 900, 10));

        jLabel5.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel5.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 900, 10));

        vistaLoteAcerrar.add(jPanel10);

        jbtnAbrirInventario3.setBackground(new java.awt.Color(0, 0, 0));
        jbtnAbrirInventario3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnAbrirInventario3.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAbrirInventario3.setText("Cancelar");
        jbtnAbrirInventario3.setPreferredSize(new java.awt.Dimension(220, 25));
        jbtnAbrirInventario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAbrirInventario3ActionPerformed(evt);
            }
        });
        vistaLoteAcerrar.add(jbtnAbrirInventario3);

        jbtnGuardarCierreLote.setBackground(new java.awt.Color(0, 0, 0));
        jbtnGuardarCierreLote.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnGuardarCierreLote.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGuardarCierreLote.setText("Guardar");
        jbtnGuardarCierreLote.setPreferredSize(new java.awt.Dimension(220, 25));
        jbtnGuardarCierreLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarCierreLoteActionPerformed(evt);
            }
        });
        vistaLoteAcerrar.add(jbtnGuardarCierreLote);

        body2.add(vistaLoteAcerrar, "card2");

        body.add(body2, java.awt.BorderLayout.CENTER);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarCierreLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarCierreLoteActionPerformed
        jpa.getTransaction().begin();
        objRegistroMensualLotes.setCantidad_final(objRegistroMensualLotes.getLote_detalle().getCantidad());
        objRegistroMensualLotes.setFecha_cierre_real(new Date());
        objRegistroMensualLotes.setUsuario_cierre(objUsuario);
        jpa.createQuery("update RegistroMensualLotes set id_Usuario_cierre="+objUsuario.getId_Usuario()+"where id_Registro_mensual_lotes="+objRegistroMensualLotes.getId_Registro_mensual_lotes()).executeUpdate();
        jpa.persist(objRegistroMensualLotes);
        ConsultaBD();
        principalEjecucion();
        JOptionPane.showMessageDialog(jPanel7, "Se guardó con exito");
        vistaLoteAcerrar.setVisible(false);
        vistaRegistroLotes.setVisible(true);
        jpa.getTransaction().commit();
    }//GEN-LAST:event_jbtnGuardarCierreLoteActionPerformed

    private void jbtnDescruzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDescruzarActionPerformed

        

    }//GEN-LAST:event_jbtnDescruzarActionPerformed

    RegistroMensualLotes objRegistroMensualLotes;
    private void jtblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblVentasMouseClicked
        objRegistroMensualLotes=(RegistroMensualLotes)jtblVentas.getValueAt(jtblVentas.getSelectedRow(),0);
        
        jlblPF.setText(objRegistroMensualLotes.getLote_detalle().getInventario().getMedicamento().getNombre());
        jlblFF.setText(objRegistroMensualLotes.getLote_detalle().getInventario().getMedicamento().getForma_farmaceutica());
        jlblConc.setText(objRegistroMensualLotes.getLote_detalle().getInventario().getMedicamento().getConcentracion());
        jlblCantFinal.setText(objRegistroMensualLotes.getLote_detalle().getCantidad()+"");
        jlblCantInicial.setText(objRegistroMensualLotes.getCantidad_inicial()+"");
        jlblCodigoLote.setText(objRegistroMensualLotes.getLote_detalle().getCodigo());
        jlblFechaAperturada.setText(Herramienta.formatoFechaHoraMas1(objRegistroMensualLotes.getFecha_apertura_real()));
        jlblFechaVen.setText(Herramienta.formatoFecha(objRegistroMensualLotes.getLote_detalle().getFecha_vencimiento()));
        List<Detalle_Medicamentos> lista_Medicamentos_del_mes=
                Herramienta.findbyBeetWeen(Detalle_Medicamentos.class,"fecha", objRegistroMensualLotes.getFecha_apertura_real(), new Date(), jpa, objRegistroMensualLotes.getLote_detalle().getId_Lote_detalle());
        llenarTablaDetalleMedicamento(lista_Medicamentos_del_mes);
        vistaRegistroLotes.setVisible(false);
        vistaLoteAcerrar.setVisible(true);
    }//GEN-LAST:event_jtblVentasMouseClicked

    private void jbtnAbrirInventario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAbrirInventario3ActionPerformed
        vistaLoteAcerrar.setVisible(false);
        vistaRegistroLotes.setVisible(true);
    }//GEN-LAST:event_jbtnAbrirInventario3ActionPerformed

    private void jbtnCerrarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarInventarioActionPerformed

        int confirmado = JOptionPane.showConfirmDialog(jlblAdvertencia,
                "Si cierra ya no podrá entregar medicamentos hasta que inventaríe todos los medicamentos ¿Está seguro de continuar?");
            if (JOptionPane.OK_OPTION == confirmado){
                jpa.getTransaction().begin();
                
                for (RegistroMensualLotes registroMensualLotes : Lista_Registro_Mensual){
                    registroMensualLotes.setFecha_cierra(new Date());
                    jpa.persist(registroMensualLotes);
                }
                JOptionPane.showMessageDialog(jPanel7, "se cerró con exito");
                ConsultaBD();
                jpa.getTransaction().commit();
                
                }
            
            else{
                System.out.println("vale... no borro nada...");
            }
        
    }//GEN-LAST:event_jbtnCerrarInventarioActionPerformed

    private void jbtnDescruzarGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDescruzarGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDescruzarGeneralActionPerformed

    public void llenarTabla(List<RegistroMensualLotes> lista_Registros){ 
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Código","Producto Farmacéutico","Cant. Inic.","User Apertura.","Cant. Fin","F.V"};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false, false, false,false
                         };
                 @Override
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................          
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (RegistroMensualLotes objRegistro : lista_Registros){
                 fila_actividad[0]=objRegistro;
                 fila_actividad[1]=objRegistro.getLote_detalle().getInventario().getMedicamento().getNombre();
                 fila_actividad[2]=objRegistro.getCantidad_inicial();
                 //fila_actividad[3]=objRegistro.getLote_detalle().getPrecio_Venta_Redondeado();  
                 fila_actividad[3]=objRegistro.getUsuario_apertura().getPersona().getInfoPersona();   
                 fila_actividad[4]=objRegistro.getLote_detalle().getCantidad();   
                 fila_actividad[5]=Herramienta.formatoFecha(objRegistro.getLote_detalle().getFecha_vencimiento());  
                 modelo.addRow(fila_actividad);//agregando filas
                 }
            jtblVentas.setModel(modelo); 
            jtblVentas.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblVentas.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(5).setCellRenderer(tcr);         
            
            jtblVentas.setFont(new java.awt.Font("Tahoma", 0, 13));
            jtblVentas.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18));
            jtblVentas.getTableHeader().setBackground(Color.BLUE);
            jtblVentas.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblVentas.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblVentas.getColumnModel().getColumn(1).setPreferredWidth(210);
            jtblVentas.getColumnModel().getColumn(2).setPreferredWidth(90);
            jtblVentas.getColumnModel().getColumn(3).setPreferredWidth(200);
            jtblVentas.getColumnModel().getColumn(4).setPreferredWidth(90);
            jtblVentas.getColumnModel().getColumn(5).setPreferredWidth(140);              
            ((DefaultTableCellRenderer)jtblVentas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64      
    }   
    
    public void llenarTablaDetalleMedicamento(List<Detalle_Medicamentos> lista_Registros){ 
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Estudiante","Cantidad","Precio Total","Fecha Entrega","Q.F"};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false, false, false,false
                         };
                 @Override
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................          
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (Detalle_Medicamentos objMedicamento : lista_Registros){
                 fila_actividad[0]=objMedicamento.getReceta().getControl_Paciente().getEstudiante().getPersona().getInfoPersona();
                 fila_actividad[1]=objMedicamento.getCantidad();
                 fila_actividad[2]=objMedicamento.getPrecio_Total();
                 //fila_actividad[3]=objRegistro.getLote_detalle().getPrecio_Venta_Redondeado();  
                 fila_actividad[3]=Herramienta.formatoFechaHoraMas1(objMedicamento.getFecha());   
                 fila_actividad[4]=objMedicamento.getUsuario().getPersona().getInfoPersona();
                 //fila_actividad[5]=Herramienta.formatoFecha(objRegistro.getLote_detalle().getFecha_vencimiento());  
                 modelo.addRow(fila_actividad);//agregando filas
                 }
            jtblDetalleMedicamento.setModel(modelo); 
            jtblDetalleMedicamento.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblDetalleMedicamento.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblDetalleMedicamento.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblDetalleMedicamento.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblDetalleMedicamento.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jtblDetalleMedicamento.getColumnModel().getColumn(4).setCellRenderer(tcr);
            
            jtblDetalleMedicamento.setFont(new java.awt.Font("Tahoma", 0, 13));
            jtblDetalleMedicamento.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18));
            jtblDetalleMedicamento.getTableHeader().setBackground(Color.BLUE);
            jtblDetalleMedicamento.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblDetalleMedicamento.getColumnModel().getColumn(0).setPreferredWidth(200);
            jtblDetalleMedicamento.getColumnModel().getColumn(1).setPreferredWidth(90);
            jtblDetalleMedicamento.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtblDetalleMedicamento.getColumnModel().getColumn(3).setPreferredWidth(120);
            jtblDetalleMedicamento.getColumnModel().getColumn(4).setPreferredWidth(150);
            ((DefaultTableCellRenderer)jtblDetalleMedicamento.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel body2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnAbrirInventario3;
    private javax.swing.JButton jbtnCerrarInventario;
    private javax.swing.JButton jbtnDescruzar;
    private javax.swing.JButton jbtnDescruzarGeneral;
    private javax.swing.JButton jbtnGuardarCierreLote;
    private javax.swing.JLabel jlblAdverte;
    private javax.swing.JLabel jlblAdvertencia;
    private javax.swing.JLabel jlblCantFinal;
    private javax.swing.JLabel jlblCantInicial;
    private javax.swing.JLabel jlblCodigoLote;
    private javax.swing.JLabel jlblConc;
    private javax.swing.JLabel jlblFF;
    private javax.swing.JLabel jlblFechaAperturada;
    private javax.swing.JLabel jlblFechaVen;
    private javax.swing.JLabel jlblPF;
    private javax.swing.JTable jtblDetalleMedicamento;
    private javax.swing.JTable jtblVentas;
    private javax.swing.JPanel vistaLoteAcerrar;
    private javax.swing.JPanel vistaRegistroLotes;
    // End of variables declaration//GEN-END:variables

}
