package com.ecoedu.Vistas.Inventario;


import com.ecoedu.model.Lote_detalle;
import com.ecoedu.model.Rol;
import com.ecoedu.model.Usuario;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */
public class Descargo extends javax.swing.JPanel {  
   // List<Detalle_control_paciente> lista_Detalles_control_paciente;
    EntityManager jpa;
    Usuario objUsuario;
    List<Rol> Lista_RolDescargo;
    List<Lote_detalle> Lista_LotesVencidos;
    TextAutoCompleter TextAutoCompleterLotes;
    List<Lote_detalle> listaLotes;
    List<Lote_detalle> Lista_CarritosDeVencidos=new ArrayList<>();
    public Descargo(EntityManager objJPA, Usuario obj) {
        initComponents();
        llenarTabla(new ArrayList<Lote_detalle>());
        this.jpa=objJPA;
        this.objUsuario=obj;
        this.TextAutoCompleterLotes=new TextAutoCompleter(jtfCodigoLotePerdida, new AutoCompleterCallback(){
            @Override
            public void callback(Object o){
                }}); 
;    
       // llenarTabla(lista_Detalles_control_paciente);
   
    }
    public void ConsultaBD(){
        Lista_RolDescargo=jpa.createQuery("SELECT p FROM Rol p where id_tipo_Roles=11").getResultList();
        Lista_LotesVencidos=jpa.createQuery("SELECT p FROM Lote_detalle p where fecha_vencimiento <= GETDATE()").getResultList();  
//lista_Detalles_control_paciente=query1.getResultList();  
    }
    public void principalEjecucion(){
        jcbTipoDescargo.removeAllItems();
        jcbLotesVencidos.removeAllItems();
        for (Rol rol : Lista_RolDescargo){
            jcbTipoDescargo.addItem(rol);}
        for (Lote_detalle lotesVenc : Lista_LotesVencidos){
            jcbLotesVencidos.addItem(lotesVenc);
        }
        if(Lista_LotesVencidos.isEmpty()){
            jbtnGuardarVencidos.setEnabled(false);
            jlblMensaje.setVisible(true);            
        }
        else{
            jbtnGuardarVencidos.setEnabled(true);
            jlblMensaje.setVisible(false);    
            }
    }
    public void iniciar_conVencidos(){
        for (Rol rol : Lista_RolDescargo){
            if(rol.getNombre_rol().equals("VENCIDO")){
                jcbTipoDescargo.setSelectedItem(rol);
                break;
            }            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        head2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcbTipoDescargo = new javax.swing.JComboBox<>();
        jtfCodigoDocumento = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        body2 = new javax.swing.JPanel();
        cuerpo1Vencido = new javax.swing.JPanel();
        jlblPF = new javax.swing.JLabel();
        jcbLotesVencidos = new javax.swing.JComboBox<>();
        jbtnAgregarLoteVencido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLotesSeleccionados = new javax.swing.JTable();
        jlblMensaje = new javax.swing.JLabel();
        jbtnGuardarVencidos = new javax.swing.JButton();
        jlblConc = new javax.swing.JLabel();
        jlblLotesVencidos1 = new javax.swing.JLabel();
        jlblLoteSelecionado2 = new javax.swing.JLabel();
        jlblFF = new javax.swing.JLabel();
        jlblTpf = new javax.swing.JLabel();
        jlblTff = new javax.swing.JLabel();
        jlblTConc = new javax.swing.JLabel();
        cuerpo2Faltante = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfCodigoLotePerdida = new javax.swing.JTextField();
        jtfCantidadPerdida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnGuardarFaltantes = new javax.swing.JButton();
        jlblAsteriscoCantidadPerdida = new javax.swing.JLabel();
        jlblAsteriscoCodigoLotePerdida = new javax.swing.JLabel();
        cuerpo3Donacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtnGuardarFaltantes1 = new javax.swing.JButton();
        jtfCodigoLote2 = new javax.swing.JTextField();
        jtfCodigoLote3 = new javax.swing.JTextField();
        cuerpo4Campaña = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtnGuardarFaltantes2 = new javax.swing.JButton();
        jtfCodigoLote4 = new javax.swing.JTextField();
        jtfCodigoLote5 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(207, 48, 72));
        head.setPreferredSize(new java.awt.Dimension(100, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DESCARGO");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        head2.setBackground(new java.awt.Color(255, 255, 255));
        head2.setPreferredSize(new java.awt.Dimension(890, 280));
        head2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(890, 200));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TIPO :");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CÓDIGO DOCUMENTO:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, 25));

        jcbTipoDescargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbTipoDescargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoDescargoItemStateChanged(evt);
            }
        });
        jPanel7.add(jcbTipoDescargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 230, 25));

        jtfCodigoDocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoDocumentoActionPerformed(evt);
            }
        });
        jPanel7.add(jtfCodigoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 230, 25));

        jLabel31.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel31.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 900, 10));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 700, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("MOTIVO :");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 25));

        jLabel30.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel30.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 900, 10));

        head2.add(jPanel7, java.awt.BorderLayout.CENTER);

        body.add(head2, java.awt.BorderLayout.PAGE_START);

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.setMaximumSize(new java.awt.Dimension(1990, 650));
        body2.setMinimumSize(new java.awt.Dimension(200, 200));
        body2.setPreferredSize(new java.awt.Dimension(9900, 320));
        body2.setLayout(new java.awt.CardLayout());

        cuerpo1Vencido.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo1Vencido.setPreferredSize(new java.awt.Dimension(900, 350));
        cuerpo1Vencido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblPF.setForeground(new java.awt.Color(0, 0, 255));
        jlblPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuerpo1Vencido.add(jlblPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 540, 25));

        jcbLotesVencidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbLotesVencidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLotesVencidosItemStateChanged(evt);
            }
        });
        cuerpo1Vencido.add(jcbLotesVencidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, 25));

        jbtnAgregarLoteVencido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnAgregarLoteVencido.setText("+");
        jbtnAgregarLoteVencido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarLoteVencidoActionPerformed(evt);
            }
        });
        cuerpo1Vencido.add(jbtnAgregarLoteVencido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 50, 25));

        jtblLotesSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jtblLotesSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblLotesSeleccionadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblLotesSeleccionados);

        cuerpo1Vencido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 230, 110));

        jlblMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        jlblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMensaje.setText("NO HAY NINGÚN LOTE VENCIDO");
        cuerpo1Vencido.add(jlblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 25));

        jbtnGuardarVencidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGuardarVencidos.setText("Guardar");
        jbtnGuardarVencidos.setPreferredSize(new java.awt.Dimension(100, 25));
        cuerpo1Vencido.add(jbtnGuardarVencidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 25));

        jlblConc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblConc.setForeground(new java.awt.Color(0, 0, 255));
        cuerpo1Vencido.add(jlblConc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 110, 25));

        jlblLotesVencidos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblLotesVencidos1.setText("LOTES VENCIDOS :");
        cuerpo1Vencido.add(jlblLotesVencidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 25));

        jlblLoteSelecionado2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblLoteSelecionado2.setText("LOTES SELECCIONADOS :");
        cuerpo1Vencido.add(jlblLoteSelecionado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, 25));

        jlblFF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblFF.setForeground(new java.awt.Color(0, 0, 255));
        cuerpo1Vencido.add(jlblFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 80, 25));

        jlblTpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTpf.setText("P.F:");
        cuerpo1Vencido.add(jlblTpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 25));

        jlblTff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTff.setText("F.F :");
        cuerpo1Vencido.add(jlblTff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 25));

        jlblTConc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTConc.setText("Conc :");
        cuerpo1Vencido.add(jlblTConc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 25));

        body2.add(cuerpo1Vencido, "card2");

        cuerpo2Faltante.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo2Faltante.setPreferredSize(new java.awt.Dimension(900, 350));
        cuerpo2Faltante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cuerpo2FaltanteKeyReleased(evt);
            }
        });
        cuerpo2Faltante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CANTIDAD :");
        cuerpo2Faltante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 25));

        jtfCodigoLotePerdida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoLotePerdida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoLotePerdida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoLotePerdidaActionPerformed(evt);
            }
        });
        jtfCodigoLotePerdida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoLotePerdidaKeyReleased(evt);
            }
        });
        cuerpo2Faltante.add(jtfCodigoLotePerdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 230, 25));

        jtfCantidadPerdida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCantidadPerdida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCantidadPerdida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCantidadPerdidaActionPerformed(evt);
            }
        });
        jtfCantidadPerdida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCantidadPerdidaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCantidadPerdidaKeyTyped(evt);
            }
        });
        cuerpo2Faltante.add(jtfCantidadPerdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 180, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CÓDIGO LOTE :");
        cuerpo2Faltante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CANTIDAD :");
        cuerpo2Faltante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 25));

        jbtnGuardarFaltantes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGuardarFaltantes.setText("Guardar");
        jbtnGuardarFaltantes.setPreferredSize(new java.awt.Dimension(100, 25));
        cuerpo2Faltante.add(jbtnGuardarFaltantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 25));

        jlblAsteriscoCantidadPerdida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblAsteriscoCantidadPerdida.setForeground(new java.awt.Color(255, 0, 0));
        jlblAsteriscoCantidadPerdida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAsteriscoCantidadPerdida.setText("*");
        cuerpo2Faltante.add(jlblAsteriscoCantidadPerdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 15, 25));

        jlblAsteriscoCodigoLotePerdida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblAsteriscoCodigoLotePerdida.setForeground(new java.awt.Color(255, 0, 0));
        jlblAsteriscoCodigoLotePerdida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblAsteriscoCodigoLotePerdida.setText("*");
        cuerpo2Faltante.add(jlblAsteriscoCodigoLotePerdida, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 15, 25));

        body2.add(cuerpo2Faltante, "card2");

        cuerpo3Donacion.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo3Donacion.setPreferredSize(new java.awt.Dimension(900, 350));
        cuerpo3Donacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CÓDIGO LOTE :");
        cuerpo3Donacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CANTIDAD :");
        cuerpo3Donacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 25));

        jbtnGuardarFaltantes1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGuardarFaltantes1.setText("Guardar");
        jbtnGuardarFaltantes1.setPreferredSize(new java.awt.Dimension(100, 25));
        cuerpo3Donacion.add(jbtnGuardarFaltantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 25));

        jtfCodigoLote2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoLote2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoLote2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoLote2ActionPerformed(evt);
            }
        });
        cuerpo3Donacion.add(jtfCodigoLote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 230, 25));

        jtfCodigoLote3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoLote3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoLote3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoLote3ActionPerformed(evt);
            }
        });
        cuerpo3Donacion.add(jtfCodigoLote3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 180, 25));

        body2.add(cuerpo3Donacion, "card2");

        cuerpo4Campaña.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo4Campaña.setPreferredSize(new java.awt.Dimension(900, 350));
        cuerpo4Campaña.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CÓDIGO LOTE :");
        cuerpo4Campaña.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("CANTIDAD :");
        cuerpo4Campaña.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 25));

        jbtnGuardarFaltantes2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGuardarFaltantes2.setText("Guardar");
        jbtnGuardarFaltantes2.setPreferredSize(new java.awt.Dimension(100, 25));
        cuerpo4Campaña.add(jbtnGuardarFaltantes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 25));

        jtfCodigoLote4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoLote4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoLote4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoLote4ActionPerformed(evt);
            }
        });
        cuerpo4Campaña.add(jtfCodigoLote4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 230, 25));

        jtfCodigoLote5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoLote5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoLote5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoLote5ActionPerformed(evt);
            }
        });
        cuerpo4Campaña.add(jtfCodigoLote5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 180, 25));

        body2.add(cuerpo4Campaña, "card2");

        body.add(body2, java.awt.BorderLayout.CENTER);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoDocumentoActionPerformed

    private void jtfCodigoLotePerdidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoLotePerdidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoLotePerdidaActionPerformed

    private void jtfCantidadPerdidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCantidadPerdidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCantidadPerdidaActionPerformed

    private void jcbTipoDescargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoDescargoItemStateChanged
           if(((Rol)jcbTipoDescargo.getSelectedItem())!=null){
               switch(((Rol)jcbTipoDescargo.getSelectedItem()).getNombre_rol()){
                   case "PÉRDIDA":                       
                       cuerpo3Donacion.setVisible(false);
                       cuerpo1Vencido.setVisible(false);
                       cuerpo4Campaña.setVisible(false);
                       cuerpo2Faltante.setVisible(true);
                       TextAutoCompleterLotes.removeAllItems();
                       listaLotes=jpa.createQuery("SELECT p FROM Lote_detalle p where isVencido=0").getResultList();
                       for (Lote_detalle listaLote : listaLotes){
                           TextAutoCompleterLotes.addItem(listaLote);}
                       
                       break;
                   case "DONACIÓN":
                       cuerpo4Campaña.setVisible(false);
                       cuerpo1Vencido.setVisible(false);
                       cuerpo2Faltante.setVisible(false);
                       cuerpo3Donacion.setVisible(true);
                       break;
                   case "VENCIDO":
                       cuerpo4Campaña.setVisible(false);
                       cuerpo3Donacion.setVisible(false);
                       cuerpo1Vencido.setVisible(true);
                       cuerpo2Faltante.setVisible(false);
                       break;
                   case "CAMPAÑA":   
                       cuerpo3Donacion.setVisible(false);
                       cuerpo1Vencido.setVisible(false);
                       cuerpo4Campaña.setVisible(true);
                       cuerpo2Faltante.setVisible(false);
                   default:
                       System.out.println("no reconoce ninguno");
                       }
               
               }
    }//GEN-LAST:event_jcbTipoDescargoItemStateChanged

    private void jcbLotesVencidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLotesVencidosItemStateChanged
        if(((Lote_detalle)jcbLotesVencidos.getSelectedItem())!=null){
            Lote_detalle obj=(Lote_detalle)jcbLotesVencidos.getSelectedItem();
            jlblConc.setVisible(true);
            jlblFF.setVisible(true);
            jlblPF.setVisible(true);
            jlblTConc.setVisible(true);
            jlblTff.setVisible(true);
            jlblTpf.setVisible(true);
            jlblConc.setText(obj.getInventario().getMedicamento().getConcentracion());
            jlblFF.setText(obj.getInventario().getMedicamento().getForma_farmaceutica());
            jlblPF.setText(obj.getInventario().getMedicamento().getNombre());
        }
        else{
            jlblConc.setVisible(false);
            jlblFF.setVisible(false);
            jlblPF.setVisible(false);
            jlblTConc.setVisible(false);
            jlblTff.setVisible(false);
            jlblTpf.setVisible(false);
        }
    }//GEN-LAST:event_jcbLotesVencidosItemStateChanged

    private void jbtnAgregarLoteVencidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarLoteVencidoActionPerformed
        if(jcbLotesVencidos.getSelectedItem()!=null){
            Lote_detalle objLote=(Lote_detalle)jcbLotesVencidos.getSelectedItem();
            jcbLotesVencidos.removeItem(objLote);
            Lista_CarritosDeVencidos.add(objLote);
            llenarTabla(Lista_CarritosDeVencidos);            
        }
        
    }//GEN-LAST:event_jbtnAgregarLoteVencidoActionPerformed

    private void jtblLotesSeleccionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblLotesSeleccionadosMouseClicked
         
        Lote_detalle objLote_Detalle =(Lote_detalle)jtblLotesSeleccionados.getValueAt(jtblLotesSeleccionados.getSelectedRow(),0);
        jcbLotesVencidos.addItem(objLote_Detalle);
        Lista_CarritosDeVencidos.remove(objLote_Detalle);
        llenarTabla(Lista_CarritosDeVencidos);
        
        

    }//GEN-LAST:event_jtblLotesSeleccionadosMouseClicked

    private void jtfCodigoLote2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoLote2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoLote2ActionPerformed

    private void jtfCodigoLote3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoLote3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoLote3ActionPerformed

    private void jtfCodigoLote4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoLote4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoLote4ActionPerformed

    private void jtfCodigoLote5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoLote5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoLote5ActionPerformed

    private void jtfCodigoLotePerdidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoLotePerdidaKeyReleased
           for (Lote_detalle listaLote : listaLotes){
               if(listaLote.getCodigo().equals(jtfCodigoLotePerdida.getText())){
                   jlblAsteriscoCodigoLotePerdida.setText("");
                   break;
               }
               jlblAsteriscoCodigoLotePerdida.setText("*");
               }
        
    }//GEN-LAST:event_jtfCodigoLotePerdidaKeyReleased

    private void cuerpo2FaltanteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuerpo2FaltanteKeyReleased
              
            
    }//GEN-LAST:event_cuerpo2FaltanteKeyReleased

    private void jtfCantidadPerdidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantidadPerdidaKeyReleased
        if(jtfCantidadPerdida.getText().isEmpty()){
            jlblAsteriscoCantidadPerdida.setText("*");
        }else{
            jlblAsteriscoCantidadPerdida.setText("");
        }
    }//GEN-LAST:event_jtfCantidadPerdidaKeyReleased

    private void jtfCantidadPerdidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantidadPerdidaKeyTyped
        char validar=evt.getKeyChar();
        if(!Character.isDigit(validar)){
          
                evt.consume();  
                
            }     
        
        if (jtfCantidadPerdida.getText().length()>=3){ 
         evt.consume(); 
         }
        if(' '==evt.getKeyChar()){
            evt.consume();
        }
    }//GEN-LAST:event_jtfCantidadPerdidaKeyTyped

    public void llenarTabla(List<Lote_detalle> Lista_CarritoLote){ 
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Código","Cantidad"};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false, false, false
                         };
                 @Override
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (Lote_detalle objLote: Lista_CarritoLote){
                 fila_actividad[0]=objLote;
                 fila_actividad[1]=objLote.getCantidad();   
                   
                 modelo.addRow(fila_actividad);//agregando filas
                 }
            jtblLotesSeleccionados.setModel(modelo); 
            jtblLotesSeleccionados.setGridColor(Color.BLACK);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblLotesSeleccionados.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblLotesSeleccionados.getColumnModel().getColumn(1).setCellRenderer(tcr);
           
            jtblLotesSeleccionados.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblLotesSeleccionados.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblLotesSeleccionados.getTableHeader().setBackground(Color.BLUE);
            jtblLotesSeleccionados.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblLotesSeleccionados.getColumnModel().getColumn(0).setPreferredWidth(150);
            jtblLotesSeleccionados.getColumnModel().getColumn(1).setPreferredWidth(200);          
            ((DefaultTableCellRenderer)jtblLotesSeleccionados.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64       
    }   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel body2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cuerpo1Vencido;
    private javax.swing.JPanel cuerpo2Faltante;
    private javax.swing.JPanel cuerpo3Donacion;
    private javax.swing.JPanel cuerpo4Campaña;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnAgregarLoteVencido;
    private javax.swing.JButton jbtnGuardarFaltantes;
    private javax.swing.JButton jbtnGuardarFaltantes1;
    private javax.swing.JButton jbtnGuardarFaltantes2;
    private javax.swing.JButton jbtnGuardarVencidos;
    private javax.swing.JComboBox<Lote_detalle> jcbLotesVencidos;
    private javax.swing.JComboBox<Rol> jcbTipoDescargo;
    private javax.swing.JLabel jlblAsteriscoCantidadPerdida;
    private javax.swing.JLabel jlblAsteriscoCodigoLotePerdida;
    private javax.swing.JLabel jlblConc;
    private javax.swing.JLabel jlblFF;
    private javax.swing.JLabel jlblLoteSelecionado2;
    private javax.swing.JLabel jlblLotesVencidos1;
    private javax.swing.JLabel jlblMensaje;
    private javax.swing.JLabel jlblPF;
    private javax.swing.JLabel jlblTConc;
    private javax.swing.JLabel jlblTff;
    private javax.swing.JLabel jlblTpf;
    private javax.swing.JTable jtblLotesSeleccionados;
    private javax.swing.JTextField jtfCantidadPerdida;
    private javax.swing.JTextField jtfCodigoDocumento;
    private javax.swing.JTextField jtfCodigoLote2;
    private javax.swing.JTextField jtfCodigoLote3;
    private javax.swing.JTextField jtfCodigoLote4;
    private javax.swing.JTextField jtfCodigoLote5;
    private javax.swing.JTextField jtfCodigoLotePerdida;
    // End of variables declaration//GEN-END:variables

    
    
    
    

}
