package com.ecoedu.Vistas.Inventario;


import com.ecoedu.model.Lote_detalle;
import com.ecoedu.model.Rol;
import com.ecoedu.model.Usuario;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.util.List;
import javax.persistence.EntityManager;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */
public class Descargo extends javax.swing.JPanel {  
   // List<Detalle_control_paciente> lista_Detalles_control_paciente;
    EntityManager jpa;
    Usuario objUsuario;
    List<Rol> Lista_RolDescargo;
    List<Lote_detalle> Lista_LotesVencidos;
    TextAutoCompleter TextAutoCompleterLotes;
    public Descargo(EntityManager objJPA, Usuario obj) {
        initComponents();
        this.jpa=objJPA;
        this.objUsuario=obj;
        this.TextAutoCompleterLotes=new TextAutoCompleter(jtfCodigoLote, new AutoCompleterCallback(){
            @Override
            public void callback(Object o){
                }}); 
;    
       // llenarTabla(lista_Detalles_control_paciente);
   
    }
    public void ConsultaBD(){
        Lista_RolDescargo=jpa.createQuery("SELECT p FROM Rol p where id_tipo_Roles=1002").getResultList();
        Lista_LotesVencidos=jpa.createQuery("SELECT p FROM Lote_detalle p where fecha_vencimiento <= GETDATE()").getResultList();
        
//lista_Detalles_control_paciente=query1.getResultList();
        
    }
    public void principalEjecucion(){
        jcbTipoDescargo.removeAllItems();
        jcbLotesVencidos.removeAllItems();
        for (Rol rol : Lista_RolDescargo){
            jcbTipoDescargo.addItem(rol);}
        for (Lote_detalle lotesVenc : Lista_LotesVencidos){
            jcbLotesVencidos.addItem(lotesVenc);
        }
        if(Lista_LotesVencidos.isEmpty()){
            jbtnGuardarVencidos.setEnabled(false);
            jlblMensaje.setVisible(true);            
        }
        else{
            jbtnGuardarVencidos.setEnabled(true);
            jlblMensaje.setVisible(false);    
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        head2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcbTipoDescargo = new javax.swing.JComboBox<>();
        jtfCodigoDocumento = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        body2 = new javax.swing.JPanel();
        cuerpo1Vencido = new javax.swing.JPanel();
        jlblPF = new javax.swing.JLabel();
        jcbLotesVencidos = new javax.swing.JComboBox<>();
        jbtnAgregarLoteVencido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLoteVencido = new javax.swing.JTable();
        jlblMensaje = new javax.swing.JLabel();
        jbtnGuardarVencidos = new javax.swing.JButton();
        jlblConc = new javax.swing.JLabel();
        jlblLotesVencidos1 = new javax.swing.JLabel();
        jlblLoteSelecionado2 = new javax.swing.JLabel();
        jlblFF = new javax.swing.JLabel();
        jlblTpf = new javax.swing.JLabel();
        jlblTff = new javax.swing.JLabel();
        jlblTConc = new javax.swing.JLabel();
        cuerpo2Faltante = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfCodigoLote = new javax.swing.JTextField();
        jtfCodigoLote1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnGuardarFaltantes = new javax.swing.JButton();
        cuerpo3Donacion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbtnGuardarFaltantes1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(990, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(207, 48, 72));
        head.setPreferredSize(new java.awt.Dimension(100, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DESCARGO");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.BorderLayout());

        head2.setBackground(new java.awt.Color(255, 255, 255));
        head2.setPreferredSize(new java.awt.Dimension(890, 280));
        head2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(890, 200));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TIPO :");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CÓDIGO DOCUMENTO:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, 25));

        jcbTipoDescargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbTipoDescargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoDescargoItemStateChanged(evt);
            }
        });
        jPanel7.add(jcbTipoDescargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 230, 25));

        jtfCodigoDocumento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoDocumentoActionPerformed(evt);
            }
        });
        jPanel7.add(jtfCodigoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 230, 25));

        jLabel31.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel31.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 900, 10));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 700, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("MOTIVO :");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 25));

        jLabel30.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel30.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 900, 10));

        head2.add(jPanel7, java.awt.BorderLayout.CENTER);

        body.add(head2, java.awt.BorderLayout.PAGE_START);

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.setMaximumSize(new java.awt.Dimension(1990, 650));
        body2.setMinimumSize(new java.awt.Dimension(200, 200));
        body2.setPreferredSize(new java.awt.Dimension(9900, 320));
        body2.setLayout(new java.awt.CardLayout());

        cuerpo1Vencido.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo1Vencido.setPreferredSize(new java.awt.Dimension(900, 350));
        cuerpo1Vencido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblPF.setForeground(new java.awt.Color(0, 0, 255));
        jlblPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuerpo1Vencido.add(jlblPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 540, 25));

        jcbLotesVencidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbLotesVencidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbLotesVencidosItemStateChanged(evt);
            }
        });
        cuerpo1Vencido.add(jcbLotesVencidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, 25));

        jbtnAgregarLoteVencido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnAgregarLoteVencido.setText("+");
        cuerpo1Vencido.add(jbtnAgregarLoteVencido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 50, 25));

        jtblLoteVencido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jtblLoteVencido);

        cuerpo1Vencido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 230, 110));

        jlblMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        jlblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMensaje.setText("NO HAY NINGÚN LOTE VENCIDO");
        cuerpo1Vencido.add(jlblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 900, 25));

        jbtnGuardarVencidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGuardarVencidos.setText("Guardar");
        jbtnGuardarVencidos.setPreferredSize(new java.awt.Dimension(100, 25));
        cuerpo1Vencido.add(jbtnGuardarVencidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 25));

        jlblConc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblConc.setForeground(new java.awt.Color(0, 0, 255));
        cuerpo1Vencido.add(jlblConc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 110, 25));

        jlblLotesVencidos1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblLotesVencidos1.setText("LOTES VENCIDOS :");
        cuerpo1Vencido.add(jlblLotesVencidos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 25));

        jlblLoteSelecionado2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblLoteSelecionado2.setText("LOTES SELECCIONADOS :");
        cuerpo1Vencido.add(jlblLoteSelecionado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 25));

        jlblFF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblFF.setForeground(new java.awt.Color(0, 0, 255));
        cuerpo1Vencido.add(jlblFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 80, 25));

        jlblTpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTpf.setText("P.F:");
        cuerpo1Vencido.add(jlblTpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 25));

        jlblTff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTff.setText("F.F :");
        cuerpo1Vencido.add(jlblTff, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 25));

        jlblTConc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblTConc.setText("Conc :");
        cuerpo1Vencido.add(jlblTConc, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 25));

        body2.add(cuerpo1Vencido, "card2");

        cuerpo2Faltante.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo2Faltante.setPreferredSize(new java.awt.Dimension(900, 350));
        cuerpo2Faltante.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CANTIDAD :");
        cuerpo2Faltante.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 25));

        jtfCodigoLote.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoLoteActionPerformed(evt);
            }
        });
        cuerpo2Faltante.add(jtfCodigoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 230, 25));

        jtfCodigoLote1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfCodigoLote1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoLote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoLote1ActionPerformed(evt);
            }
        });
        cuerpo2Faltante.add(jtfCodigoLote1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 180, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("CÓDIGO LOTE :");
        cuerpo2Faltante.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("CANTIDAD :");
        cuerpo2Faltante.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 25));

        jbtnGuardarFaltantes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGuardarFaltantes.setText("Guardar");
        jbtnGuardarFaltantes.setPreferredSize(new java.awt.Dimension(100, 25));
        cuerpo2Faltante.add(jbtnGuardarFaltantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 25));

        body2.add(cuerpo2Faltante, "card2");

        cuerpo3Donacion.setBackground(new java.awt.Color(255, 255, 255));
        cuerpo3Donacion.setPreferredSize(new java.awt.Dimension(900, 350));
        cuerpo3Donacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CÓDIGO LOTE :");
        cuerpo3Donacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("CANTIDAD :");
        cuerpo3Donacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, 25));

        jbtnGuardarFaltantes1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnGuardarFaltantes1.setText("Guardar");
        jbtnGuardarFaltantes1.setPreferredSize(new java.awt.Dimension(100, 25));
        cuerpo3Donacion.add(jbtnGuardarFaltantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, 25));

        body2.add(cuerpo3Donacion, "card2");

        body.add(body2, java.awt.BorderLayout.CENTER);

        add(body, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoDocumentoActionPerformed

    private void jtfCodigoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoLoteActionPerformed

    private void jtfCodigoLote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoLote1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoLote1ActionPerformed

    private void jcbTipoDescargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoDescargoItemStateChanged
           if(((Rol)jcbTipoDescargo.getSelectedItem())!=null){
               switch(((Rol)jcbTipoDescargo.getSelectedItem()).getNombre_rol()){
                   case "PÉRDIDA":
                       cuerpo3Donacion.setVisible(false);
                       cuerpo1Vencido.setVisible(false);
                       cuerpo2Faltante.setVisible(true);
                       List<Lote_detalle> listaLotes=jpa.createQuery("SELECT p FROM Lote_detalle p where isVencido=0").getResultList();
                       for (Lote_detalle listaLote : listaLotes){
                           TextAutoCompleterLotes.addItem(listaLote);}
                       break;
                   case "DONACIÓN":
                       cuerpo3Donacion.setVisible(true);
                       cuerpo1Vencido.setVisible(false);
                       cuerpo2Faltante.setVisible(false);
                       break;
                   case "VENCIDO":
                       cuerpo3Donacion.setVisible(false);
                       cuerpo1Vencido.setVisible(true);
                       cuerpo2Faltante.setVisible(false);
                       break;
                       }
               }
    }//GEN-LAST:event_jcbTipoDescargoItemStateChanged

    private void jcbLotesVencidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbLotesVencidosItemStateChanged
        if(((Lote_detalle)jcbLotesVencidos.getSelectedItem())!=null){
            Lote_detalle obj=(Lote_detalle)jcbLotesVencidos.getSelectedItem();
            jlblConc.setVisible(true);
            jlblFF.setVisible(true);
            jlblPF.setVisible(true);
            jlblTConc.setVisible(true);
            jlblTff.setVisible(true);
            jlblTpf.setVisible(true);
            jlblConc.setText(obj.getInventario().getMedicamento().getConcentracion());
            jlblFF.setText(obj.getInventario().getMedicamento().getForma_farmaceutica());
            jlblPF.setText(obj.getInventario().getMedicamento().getNombre());
        }
        else{
            jlblConc.setVisible(false);
            jlblFF.setVisible(false);
            jlblPF.setVisible(false);
            jlblTConc.setVisible(false);
            jlblTff.setVisible(false);
            jlblTpf.setVisible(false);
        }
    }//GEN-LAST:event_jcbLotesVencidosItemStateChanged
/*
    public void llenarTabla(List<Detalle_control_paciente> listaDetalleControl){ 
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Fecha","Producto Farmacéutico","Cantidad","Precio Unidad","Código Estudiante","Química(o) Farmacéutica(o)"};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false, false, false
                         };
                 @Override
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < listaDetalleControl.size(); i++){
                 System.out.println("entro");
                 fila_actividad[0]=listaDetalleControl.get(i).getFecha();
                 fila_actividad[1]=listaDetalleControl.get(i).getId_Medicamento().getNombre();             
                 fila_actividad[2]=listaDetalleControl.get(i).getCantidad();  
                 fila_actividad[3]=listaDetalleControl.get(i).getPrecio_Unitario();   
                 fila_actividad[4]=listaDetalleControl.get(i).getControl_Paciente().getPersona().getCodigo();   
                 fila_actividad[5]=listaDetalleControl.get(i).getUsuario().getPersona().getInfoPersona();  
                 modelo.addRow(fila_actividad);//agregando filas
                 }
            jtblVentas.setModel(modelo); 
            jtblVentas.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblVentas.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jtblVentas.getColumnModel().getColumn(5).setCellRenderer(tcr);
            
            jtblVentas.getColumnModel().getColumn(5).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(4).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(3).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(2).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(1).setPreferredWidth(40);
            jtblVentas.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtblVentas.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblVentas.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblVentas.getTableHeader().setBackground(Color.BLUE);
            jtblVentas.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblVentas.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblVentas.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblVentas.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtblVentas.getColumnModel().getColumn(3).setPreferredWidth(125);
            jtblVentas.getColumnModel().getColumn(4).setPreferredWidth(90);
            jtblVentas.getColumnModel().getColumn(5).setPreferredWidth(220);
            
            ((DefaultTableCellRenderer)jtblVentas.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64
            

    
           
    }   */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel body2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cuerpo1Vencido;
    private javax.swing.JPanel cuerpo2Faltante;
    private javax.swing.JPanel cuerpo3Donacion;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnAgregarLoteVencido;
    private javax.swing.JButton jbtnGuardarFaltantes;
    private javax.swing.JButton jbtnGuardarFaltantes1;
    private javax.swing.JButton jbtnGuardarVencidos;
    private javax.swing.JComboBox<Lote_detalle> jcbLotesVencidos;
    private javax.swing.JComboBox<Rol> jcbTipoDescargo;
    private javax.swing.JLabel jlblConc;
    private javax.swing.JLabel jlblFF;
    private javax.swing.JLabel jlblLoteSelecionado2;
    private javax.swing.JLabel jlblLotesVencidos1;
    private javax.swing.JLabel jlblMensaje;
    private javax.swing.JLabel jlblPF;
    private javax.swing.JLabel jlblTConc;
    private javax.swing.JLabel jlblTff;
    private javax.swing.JLabel jlblTpf;
    private javax.swing.JTable jtblLoteVencido;
    private javax.swing.JTextField jtfCodigoDocumento;
    private javax.swing.JTextField jtfCodigoLote;
    private javax.swing.JTextField jtfCodigoLote1;
    // End of variables declaration//GEN-END:variables

    
    
    
    

}
