package com.ecoedu.Vistas.Inventario;


import com.ecoedu.Vistas.vista_base.Principal;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.ecoedu.model.Inventario;
import java.util.ArrayList;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */

/*
1-agregar registrar un medicamento nuevo,cantidad,precio;
2-agregar cantidad a un medicamento ya existente;
3-Modificar precio Unitario de un Medicamento ya existente;
*/
public class InventarioOper extends javax.swing.JPanel {   
    List<Inventario> Lista_Inventario;
    EntityManager jpa;
    Principal objPrincipal;
    public InventarioOper(EntityManager objJPA,Principal OBJPrincipal) {
        initComponents();
        this.jpa=objJPA;
        this.objPrincipal=OBJPrincipal;
        ConsultaBD();
        principalEjecucion(); 
           
    }
    public void ConsultaBD(){
        Query query1=jpa.createQuery("SELECT p FROM Inventario p");
        Lista_Inventario=query1.getResultList();      
    }   
    public void principalEjecucion(){
        
        jtfProductoFarmaceutico.setEnabled(false);
        jtfPrecioUnitarioVenta.setEnabled(false);
        llenar_tabla_de_inventarioOperaciones(getMedicamentosParecidos(""));
        llenar_tabla_de_inventario(Lista_Inventario);
        
    }
    public List<Inventario> getMedicamentosParecidos(String palabra){
        List<Inventario> listaInventario=new ArrayList<>();
        for (int n = 0; n < Lista_Inventario.size(); n++) {
            boolean aux=true;
            for (int i = 0; i<palabra.length(); i++) {
               
                if(palabra.charAt(i)!=Lista_Inventario.get(n).getId_Medicamento().getNombre().charAt(i)){
                    aux=false;
                    break;                   
                }            
            }
            if(aux){
                listaInventario.add(Lista_Inventario.get(n));
            }
        }
        return listaInventario;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bodyCard = new javax.swing.JPanel();
        vista1 = new javax.swing.JPanel();
        head2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        body2 = new javax.swing.JPanel();
        vista11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblInventario = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        vista2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtbtnAgregarMedicamento = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jtbtnModificarMedicamento = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jtbtnCrearMedicamento = new javax.swing.JToggleButton();
        headListaInventarioVoF = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblInventarioOperaciones = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jtfMedicamento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        body3 = new javax.swing.JPanel();
        vista21 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcbFechaVencimiento = new rojeru_san.componentes.RSDateChooser();
        jtfCantidad = new javax.swing.JTextField();
        jtfLote = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtfPrecioUnitarioVenta = new javax.swing.JTextField();
        jtfProductoFarmaceutico = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(0, 102, 102));
        head.setPreferredSize(new java.awt.Dimension(900, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("INVENTARIO");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        bodyCard.setLayout(new java.awt.CardLayout());

        vista1.setBackground(new java.awt.Color(255, 255, 255));
        vista1.setLayout(new java.awt.BorderLayout());

        head2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(890, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(880, 30));
        jPanel4.setRequestFocusEnabled(false);
        jPanel7.add(jPanel4);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(880, 40));
        jPanel7.add(jPanel11);

        head2.add(jPanel7);

        vista1.add(head2, java.awt.BorderLayout.PAGE_START);

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.setMaximumSize(new java.awt.Dimension(1990, 650));
        body2.setMinimumSize(new java.awt.Dimension(200, 200));
        body2.setPreferredSize(new java.awt.Dimension(9900, 520));
        body2.setLayout(new java.awt.BorderLayout());

        vista11.setBackground(new java.awt.Color(255, 255, 255));
        vista11.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(900, 290));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jtblInventario.setBorder(new javax.swing.border.MatteBorder(null));
        jtblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto"
            }
        ));
        jtblInventario.setGridColor(new java.awt.Color(0, 0, 0));
        jtblInventario.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblInventario.setPreferredSize(new java.awt.Dimension(200, 260));
        jtblInventario.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jtblInventario);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ols");
        jPanel9.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jLabel14.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jLabel18.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel18, java.awt.BorderLayout.LINE_START);

        vista11.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(900, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Detalle Inventario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);

        jLabel4.setMaximumSize(new java.awt.Dimension(500, 0));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(450, 30));
        jPanel10.add(jLabel4);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Llenar Inventario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3);

        vista11.add(jPanel10);

        body2.add(vista11, java.awt.BorderLayout.CENTER);

        vista1.add(body2, java.awt.BorderLayout.CENTER);

        bodyCard.add(vista1, "card2");

        vista2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 40));

        buttonGroup2.add(jtbtnAgregarMedicamento);
        jtbtnAgregarMedicamento.setText("AGREGAR MEDICAMENTOS");
        jtbtnAgregarMedicamento.setPreferredSize(new java.awt.Dimension(200, 23));
        jtbtnAgregarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnAgregarMedicamentoActionPerformed(evt);
            }
        });
        jPanel2.add(jtbtnAgregarMedicamento);

        jLabel3.setPreferredSize(new java.awt.Dimension(40, 14));
        jPanel2.add(jLabel3);

        buttonGroup2.add(jtbtnModificarMedicamento);
        jtbtnModificarMedicamento.setText("MODIFICAR MEDICAMENTO");
        jtbtnModificarMedicamento.setPreferredSize(new java.awt.Dimension(200, 23));
        jtbtnModificarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnModificarMedicamentoActionPerformed(evt);
            }
        });
        jPanel2.add(jtbtnModificarMedicamento);

        jLabel13.setPreferredSize(new java.awt.Dimension(40, 14));
        jPanel2.add(jLabel13);

        buttonGroup2.add(jtbtnCrearMedicamento);
        jtbtnCrearMedicamento.setText("CREAR MEDICAMENTO");
        jtbtnCrearMedicamento.setPreferredSize(new java.awt.Dimension(200, 23));
        jtbtnCrearMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbtnCrearMedicamentoActionPerformed(evt);
            }
        });
        jPanel2.add(jtbtnCrearMedicamento);

        vista2.add(jPanel2);

        headListaInventarioVoF.setBackground(new java.awt.Color(255, 255, 255));
        headListaInventarioVoF.setPreferredSize(new java.awt.Dimension(900, 200));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(890, 190));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jtblInventarioOperaciones.setBorder(new javax.swing.border.MatteBorder(null));
        jtblInventarioOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto"
            }
        ));
        jtblInventarioOperaciones.setGridColor(new java.awt.Color(0, 0, 0));
        jtblInventarioOperaciones.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblInventarioOperaciones.setPreferredSize(new java.awt.Dimension(200, 260));
        jtblInventarioOperaciones.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jtblInventarioOperaciones);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel22.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel8.add(jLabel22, java.awt.BorderLayout.LINE_START);

        jLabel21.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel8.add(jLabel21, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel37.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel37.setText("Nombre Medicamento :");
        jPanel1.add(jLabel37);

        jtfMedicamento.setPreferredSize(new java.awt.Dimension(150, 30));
        jtfMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfMedicamentoKeyReleased(evt);
            }
        });
        jPanel1.add(jtfMedicamento);

        jPanel8.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Click en el Medicamento a agregar");
        jPanel8.add(jLabel15, java.awt.BorderLayout.PAGE_END);

        headListaInventarioVoF.add(jPanel8);

        vista2.add(headListaInventarioVoF);

        body3.setBackground(new java.awt.Color(255, 255, 255));
        body3.setMaximumSize(new java.awt.Dimension(1990, 650));
        body3.setMinimumSize(new java.awt.Dimension(200, 200));
        body3.setPreferredSize(new java.awt.Dimension(900, 250));
        body3.setLayout(new java.awt.BorderLayout());

        vista21.setBackground(new java.awt.Color(255, 255, 255));
        vista21.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMinimumSize(new java.awt.Dimension(900, 170));
        jPanel13.setPreferredSize(new java.awt.Dimension(895, 140));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Producto Farmaceutico:");
        jLabel1.setPreferredSize(new java.awt.Dimension(330, 25));
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Precio Unitario de Venta:");
        jLabel8.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 190, 25));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Cantidad:");
        jLabel9.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel13.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 70, 25));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Fecha Vencimiento:");
        jLabel10.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel13.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 140, 25));

        jcbFechaVencimiento.setFormatoFecha("dd/MM/yyyy ");
        jcbFechaVencimiento.setPlaceholder("Desde ");
        jcbFechaVencimiento.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel13.add(jcbFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, 25));

        jtfCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(jtfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 90, 25));

        jtfLote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(jtfLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 25));

        jLabel7.setText("------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel7.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 890, 10));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Código del Lote:");
        jLabel17.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 25));

        jtfPrecioUnitarioVenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfPrecioUnitarioVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(jtfPrecioUnitarioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 140, 25));

        jtfProductoFarmaceutico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfProductoFarmaceutico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(jtfProductoFarmaceutico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 120, 25));

        jLabel38.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel38.setText("Llenado Inventario");
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        vista21.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(895, 45));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jPanel14.add(jButton2);

        jLabel5.setMaximumSize(new java.awt.Dimension(500, 0));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 0));
        jLabel5.setPreferredSize(new java.awt.Dimension(480, 30));
        jPanel14.add(jLabel5);

        jLabel6.setMaximumSize(new java.awt.Dimension(500, 0));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 0));
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel14.add(jLabel6);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("AGREGAR");
        jPanel14.add(jButton4);

        vista21.add(jPanel14);

        body3.add(vista21, java.awt.BorderLayout.CENTER);

        vista2.add(body3);

        bodyCard.add(vista2, "card3");

        add(bodyCard, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vista1.setVisible(false);
        vista2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMedicamentoKeyReleased
        llenar_tabla_de_inventarioOperaciones(getMedicamentosParecidos(jtfMedicamento.getText()));
    }//GEN-LAST:event_jtfMedicamentoKeyReleased

    private void jtbtnAgregarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnAgregarMedicamentoActionPerformed
        headListaInventarioVoF.setVisible(true);
        jtfProductoFarmaceutico.setEnabled(false);
        jtfPrecioUnitarioVenta.setEnabled(false);
       
        
    }//GEN-LAST:event_jtbtnAgregarMedicamentoActionPerformed

    private void jtbtnModificarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnModificarMedicamentoActionPerformed
        headListaInventarioVoF.setVisible(true);
        jtfProductoFarmaceutico.setEnabled(true);
        jtfPrecioUnitarioVenta.setEnabled(true);
        jtfLote.setEnabled(false);
        jtfCantidad.setEnabled(false);
        jcbFechaVencimiento.setEnabled(false);
    }//GEN-LAST:event_jtbtnModificarMedicamentoActionPerformed

    private void jtbtnCrearMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbtnCrearMedicamentoActionPerformed

        headListaInventarioVoF.setVisible(false);
        jtfProductoFarmaceutico.setEnabled(true);
        jtfPrecioUnitarioVenta.setEnabled(true);
    }//GEN-LAST:event_jtbtnCrearMedicamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body2;
    private javax.swing.JPanel body3;
    private javax.swing.JPanel bodyCard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head2;
    private javax.swing.JPanel headListaInventarioVoF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.componentes.RSDateChooser jcbFechaVencimiento;
    private javax.swing.JTable jtblInventario;
    private javax.swing.JTable jtblInventarioOperaciones;
    private javax.swing.JToggleButton jtbtnAgregarMedicamento;
    private javax.swing.JToggleButton jtbtnCrearMedicamento;
    private javax.swing.JToggleButton jtbtnModificarMedicamento;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfLote;
    private javax.swing.JTextField jtfMedicamento;
    private javax.swing.JTextField jtfPrecioUnitarioVenta;
    private javax.swing.JTextField jtfProductoFarmaceutico;
    private javax.swing.JPanel vista1;
    private javax.swing.JPanel vista11;
    private javax.swing.JPanel vista2;
    private javax.swing.JPanel vista21;
    // End of variables declaration//GEN-END:variables

    public void llenar_tabla_de_inventario(List<Inventario> listaInventario){
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Código","Nombre","Cantidad","Precio Unitario"}; 
             boolean[] canEdit = new boolean [] {false, false, false, false};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false
                         };
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < listaInventario.size(); i++){
                 fila_actividad[0]=listaInventario.get(i).getId_Inventario();
                 fila_actividad[1]=listaInventario.get(i).getId_Medicamento().getNombre();             
                 fila_actividad[2]=listaInventario.get(i).getCantidad();  
                 fila_actividad[3]=listaInventario.get(i).getId_Medicamento().getPrecio_Unitario();   
                 
                 modelo.addRow(fila_actividad);//agregando filas
                 }
             
            jtblInventario.setModel(modelo); 
            jtblInventario.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblInventario.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblInventario.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblInventario.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblInventario.getColumnModel().getColumn(3).setCellRenderer(tcr);
        
   
            jtblInventario.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblInventario.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblInventario.getTableHeader().setBackground(Color.BLUE);
            jtblInventario.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblInventario.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblInventario.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblInventario.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtblInventario.getColumnModel().getColumn(3).setPreferredWidth(125);            
            ((DefaultTableCellRenderer)jtblInventario.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64                  
    }
    public void llenar_tabla_de_inventarioOperaciones(List<Inventario> listaInventario){
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Código","Nombre","Cantidad","Precio Unitario"}; 
             boolean[] canEdit = new boolean [] {false, false, false, false};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false
                         };
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < listaInventario.size(); i++){
                 fila_actividad[0]=listaInventario.get(i).getId_Inventario();
                 fila_actividad[1]=listaInventario.get(i).getId_Medicamento().getNombre();             
                 fila_actividad[2]=listaInventario.get(i).getCantidad();  
                 fila_actividad[3]=listaInventario.get(i).getId_Medicamento().getPrecio_Unitario();   
                 
                 modelo.addRow(fila_actividad);//agregando filas
                 }
             
            jtblInventarioOperaciones.setModel(modelo); 
            jtblInventarioOperaciones.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblInventarioOperaciones.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblInventarioOperaciones.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblInventarioOperaciones.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblInventarioOperaciones.getColumnModel().getColumn(3).setCellRenderer(tcr);
        
   
            jtblInventarioOperaciones.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblInventarioOperaciones.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblInventarioOperaciones.getTableHeader().setBackground(Color.BLUE);
            jtblInventarioOperaciones.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblInventarioOperaciones.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblInventarioOperaciones.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblInventarioOperaciones.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtblInventarioOperaciones.getColumnModel().getColumn(3).setPreferredWidth(125);            
            ((DefaultTableCellRenderer)jtblInventarioOperaciones.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64                  
    }
    
    
    

}
