package com.ecoedu.Vistas.Inventario;


import com.ecoedu.Vistas.vista_base.Principal;
import com.ecoedu.model.Medicamento;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yrma
 */

/*
1-agregar registrar un medicamento nuevo,cantidad,precio;
2-agregar cantidad a un medicamento ya existente;
3-Modificar precio Unitario de un Medicamento ya existente;
*/
public class Inventario extends javax.swing.JPanel {   
    List<Medicamento> lista_Medicamentos;
    EntityManager jpa;
    Principal objPrincipal;
    public Inventario(EntityManager objJPA,Principal OBJPrincipal) {
        initComponents();
        this.jpa=objJPA;
        this.objPrincipal=OBJPrincipal;
        //ConsultaBD();
        //principalEjecucion();
        
        
        
        
        
           
    }
    public void ConsultaBD(){
        Query query1=jpa.createQuery("SELECT p FROM Medicamento p");
        lista_Medicamentos=query1.getResultList();
        
    }
    
    public void principalEjecucion(){
        jcbYearDesde.setVisible(false);
        jlblDesde.setVisible(false);
        jlblHasta.setVisible(false);
        jcbYearHasta.setVisible(false);
        jcbMeses.setVisible(false);
        jcbYear.setVisible(false);
        jlblMes.setVisible(false);     
        llenarTabla(lista_Medicamentos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bodyCard = new javax.swing.JPanel();
        vista1 = new javax.swing.JPanel();
        head2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jrbEspecifica1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jrbMesayo1 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jlblDesde = new javax.swing.JLabel();
        jcbYearDesde = new rojeru_san.componentes.RSDateChooser();
        jlblHasta = new javax.swing.JLabel();
        jcbYearHasta = new rojeru_san.componentes.RSDateChooser();
        jlblMes = new javax.swing.JLabel();
        jcbMeses = new javax.swing.JComboBox<>();
        jcbYear = new rojeru_san.componentes.RSYearDate();
        body2 = new javax.swing.JPanel();
        vista11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblInventario = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        vista2 = new javax.swing.JPanel();
        head3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        body3 = new javax.swing.JPanel();
        vista21 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblInventario1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(0, 102, 102));
        head.setPreferredSize(new java.awt.Dimension(900, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("INVENTARIO");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        bodyCard.setLayout(new java.awt.CardLayout());

        vista1.setBackground(new java.awt.Color(255, 255, 255));
        vista1.setLayout(new java.awt.BorderLayout());

        head2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(890, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(880, 30));
        jPanel4.setRequestFocusEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BÚSQUEDA ESPECÍFICA");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel16.setPreferredSize(new java.awt.Dimension(162, 30));
        jPanel4.add(jLabel16);

        jrbEspecifica1.setBackground(new java.awt.Color(255, 255, 255));
        jrbEspecifica1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jrbEspecifica1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbEspecifica1.setPreferredSize(new java.awt.Dimension(15, 30));
        jPanel4.add(jrbEspecifica1);

        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel2);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("BÚSQUEDA POR MES Y/O AÑO");
        jLabel19.setPreferredSize(new java.awt.Dimension(210, 30));
        jPanel4.add(jLabel19);

        jrbMesayo1.setBackground(new java.awt.Color(255, 255, 255));
        jrbMesayo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jrbMesayo1.setPreferredSize(new java.awt.Dimension(15, 30));
        jPanel4.add(jrbMesayo1);

        jPanel7.add(jPanel4);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(880, 40));

        jlblDesde.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblDesde.setText("Desde :");
        jPanel11.add(jlblDesde);

        jcbYearDesde.setFormatoFecha("dd/MM/yyyy ");
        jcbYearDesde.setPlaceholder("Desde ");
        jcbYearDesde.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel11.add(jcbYearDesde);

        jlblHasta.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblHasta.setText("Hasta :");
        jPanel11.add(jlblHasta);

        jcbYearHasta.setFormatoFecha("dd/MM/yyyy\n");
        jcbYearHasta.setPlaceholder("Hasta");
        jcbYearHasta.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel11.add(jcbYearHasta);

        jlblMes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jlblMes.setText("Mes :");
        jPanel11.add(jlblMes);

        jcbMeses.setBackground(new java.awt.Color(0, 112, 192));
        jcbMeses.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbMeses.setForeground(new java.awt.Color(67, 150, 209));
        jcbMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbMeses.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(jcbMeses);

        jcbYear.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel11.add(jcbYear);

        jPanel7.add(jPanel11);

        head2.add(jPanel7);

        vista1.add(head2, java.awt.BorderLayout.PAGE_START);

        body2.setBackground(new java.awt.Color(255, 255, 255));
        body2.setMaximumSize(new java.awt.Dimension(1990, 650));
        body2.setMinimumSize(new java.awt.Dimension(200, 200));
        body2.setPreferredSize(new java.awt.Dimension(9900, 520));
        body2.setLayout(new java.awt.BorderLayout());

        vista11.setBackground(new java.awt.Color(255, 255, 255));
        vista11.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(900, 290));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jtblInventario.setBorder(new javax.swing.border.MatteBorder(null));
        jtblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto"
            }
        ));
        jtblInventario.setGridColor(new java.awt.Color(0, 0, 0));
        jtblInventario.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblInventario.setPreferredSize(new java.awt.Dimension(200, 260));
        jtblInventario.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jtblInventario);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ols");
        jPanel9.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        jLabel14.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel14, java.awt.BorderLayout.LINE_END);

        jLabel18.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jLabel18, java.awt.BorderLayout.LINE_START);

        vista11.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(900, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Consulta E/S");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);

        jLabel4.setMaximumSize(new java.awt.Dimension(500, 0));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(450, 30));
        jPanel10.add(jLabel4);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("AGREGAR MEDICAMENTOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3);

        vista11.add(jPanel10);

        body2.add(vista11, java.awt.BorderLayout.CENTER);

        vista1.add(body2, java.awt.BorderLayout.CENTER);

        bodyCard.add(vista1, "card2");

        vista2.setBackground(new java.awt.Color(255, 255, 255));
        vista2.setLayout(new java.awt.BorderLayout());

        head3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(890, 100));
        head3.add(jPanel8);

        vista2.add(head3, java.awt.BorderLayout.PAGE_START);

        body3.setBackground(new java.awt.Color(255, 255, 255));
        body3.setMaximumSize(new java.awt.Dimension(1990, 650));
        body3.setMinimumSize(new java.awt.Dimension(200, 200));
        body3.setPreferredSize(new java.awt.Dimension(9900, 520));
        body3.setLayout(new java.awt.BorderLayout());

        vista21.setBackground(new java.awt.Color(255, 255, 255));
        vista21.setPreferredSize(new java.awt.Dimension(900, 350));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(900, 290));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jtblInventario1.setBorder(new javax.swing.border.MatteBorder(null));
        jtblInventario1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto"
            }
        ));
        jtblInventario1.setGridColor(new java.awt.Color(0, 0, 0));
        jtblInventario1.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblInventario1.setPreferredSize(new java.awt.Dimension(200, 260));
        jtblInventario1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jtblInventario1);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Tabla de Registro de Medicamentos Entregados");
        jPanel13.add(jLabel15, java.awt.BorderLayout.PAGE_END);

        jLabel21.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel13.add(jLabel21, java.awt.BorderLayout.LINE_END);

        jLabel22.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel13.add(jLabel22, java.awt.BorderLayout.LINE_START);

        vista21.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(900, 40));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Monto Total :");
        jPanel14.add(jLabel23);

        jLabel5.setMaximumSize(new java.awt.Dimension(500, 0));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 0));
        jLabel5.setPreferredSize(new java.awt.Dimension(540, 30));
        jPanel14.add(jLabel5);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VOLVER A INVENTARIO");
        jPanel14.add(jButton2);

        vista21.add(jPanel14);

        body3.add(vista21, java.awt.BorderLayout.CENTER);

        vista2.add(body3, java.awt.BorderLayout.CENTER);

        bodyCard.add(vista2, "card3");

        add(bodyCard, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vista1.setVisible(false);
        vista2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body2;
    private javax.swing.JPanel body3;
    private javax.swing.JPanel bodyCard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel head;
    private javax.swing.JPanel head2;
    private javax.swing.JPanel head3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbMeses;
    private rojeru_san.componentes.RSYearDate jcbYear;
    private rojeru_san.componentes.RSDateChooser jcbYearDesde;
    private rojeru_san.componentes.RSDateChooser jcbYearHasta;
    private javax.swing.JLabel jlblDesde;
    private javax.swing.JLabel jlblHasta;
    private javax.swing.JLabel jlblMes;
    private javax.swing.JRadioButton jrbEspecifica1;
    private javax.swing.JRadioButton jrbMesayo1;
    private javax.swing.JTable jtblInventario;
    private javax.swing.JTable jtblInventario1;
    private javax.swing.JPanel vista1;
    private javax.swing.JPanel vista11;
    private javax.swing.JPanel vista2;
    private javax.swing.JPanel vista21;
    // End of variables declaration//GEN-END:variables
public void llenarTabla(List<Medicamento> lista_Medicamento){
    System.out.println("ols");
        DefaultTableModel modelo;
        Object[] fila_actividad = null;
             //.....................................TABLA......................................
             String [] lista={"Código","Nombre","Cantidad","Precio Unitario"}; 
             boolean[] canEdit = new boolean [] {false, false, false, false};
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                     false, false, false, false
                         };
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < lista_Medicamento.size(); i++){
                 fila_actividad[0]=lista_Medicamento.get(i).getId_Medicamento();
                 fila_actividad[1]=lista_Medicamento.get(i).getNombre();             
                // fila_actividad[2]=lista_Medicamento.get(i).getCantidad();  
                 fila_actividad[3]=lista_Medicamento.get(i).getPrecio_Unitario();   
                 
                 modelo.addRow(fila_actividad);//agregando filas
                 }
             
            jtblInventario.setModel(modelo); 
            jtblInventario.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblInventario.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblInventario.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblInventario.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblInventario.getColumnModel().getColumn(3).setCellRenderer(tcr);
        
   
            jtblInventario.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblInventario.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblInventario.getTableHeader().setBackground(Color.BLUE);
            jtblInventario.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblInventario.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblInventario.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtblInventario.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtblInventario.getColumnModel().getColumn(3).setPreferredWidth(125);            
            ((DefaultTableCellRenderer)jtblInventario.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64
            

    
           
    }
    
    
    

}
