package com.ecoedu.Vistas.Inventario;


import com.ecoedu.Vistas.Herramienta;
import com.ecoedu.Vistas.vista_base.Principal;
import com.ecoedu.model.Detalle_llenado;
import com.ecoedu.model.Fabricante;
import com.ecoedu.model.Factura;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import com.ecoedu.model.Inventario;
import com.ecoedu.model.Lote_detalle;
import com.ecoedu.model.Proveedor;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/*
1-agregar registrar un medicamento nuevo,cantidad,precio;
2-agregar cantidad a un medicamento ya existente;
3-Modificar precio Unitario de un Medicamento ya existente;
*/
public class LlenarInventario extends javax.swing.JPanel {   
    String MensajeProductoFarmaceutico="";
    String MensajeFabricante="";
    List<Inventario> Lista_Inventario;    
    List<Lote_detalle> Lista_Lote_detalle_final=new ArrayList<>();
    List<Detalle_llenado> Lista_Detalle_Llenado_final=new ArrayList<>();    
    List<Proveedor> Lista_Proveedor=new ArrayList<>();//lo uso mucho
    List<Fabricante> Lista_Fabricante=new ArrayList<>();//lo uso mucho 
    EntityManager jpa;
    Principal objPrincipal;
    TextAutoCompleter autoCompleterProductoFarmaceutico;
    TextAutoCompleter autoCompleterFabricante;
    TextAutoCompleter autoCompleterProveedor;
    Inventario objInventario_final=new Inventario();        
    public LlenarInventario(EntityManager objJPA,Principal OBJPrincipal) {
        initComponents();
        this.autoCompleterProductoFarmaceutico=new TextAutoCompleter(jtfProductoFarmaceutico, new AutoCompleterCallback(){
            @Override
            public void callback(Object o){
                encontrarMedicamento((String)o);}});
        this.autoCompleterFabricante=new TextAutoCompleter(jtfFabricante,new AutoCompleterCallback() {
            @Override
            public void callback(Object o) { /*  */}});
        this.autoCompleterProveedor=new TextAutoCompleter(jtfProveedor,new AutoCompleterCallback() {
            @Override
            public void callback(Object o) {         }});
        this.jpa=objJPA;
        this.objPrincipal=OBJPrincipal;     
    }
              
    public void ConsultaBD(){
        Query query2=jpa.createQuery("SELECT p FROM Inventario p");
        Lista_Inventario=query2.getResultList();
        Query query3=jpa.createQuery("SELECT p FROM Fabricante p");
        Lista_Fabricante=query3.getResultList();        
        Query query4=jpa.createQuery("SELECT p FROM Proveedor p");
        Lista_Proveedor=query4.getResultList();
    }   
    public void principalEjecucion(){
        llenar_tabla_LoteDetalle(Lista_Lote_detalle_final, Lista_Detalle_Llenado_final);
        autoCompleterFabricante.removeAllItems();
        autoCompleterProductoFarmaceutico.removeAllItems();
        autoCompleterProveedor.removeAllItems();
        for (int i = 0; i < Lista_Inventario.size(); i++) {
            autoCompleterProductoFarmaceutico.addItem(Lista_Inventario.get(i).getId_Medicamento().getNombre());
        }   
        for (int i = 0; i < Lista_Fabricante.size(); i++) {
            autoCompleterFabricante.addItem(Lista_Fabricante.get(i).getNombre());
        }  
        for (int i = 0; i < Lista_Proveedor.size(); i++) {
            autoCompleterProveedor.addItem(Lista_Proveedor.get(i).getNombre());
        }  
        jlblFechaHoy.setText(Herramienta.formatoFechaMas1(new Date()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bodyCard = new javax.swing.JPanel();
        vistaLlenar = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlblConcentracion = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbFechaVencimiento = new rojeru_san.componentes.RSDateChooser();
        jtfPrecioUnitarioCompra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfProductoFarmaceutico = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtfCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jlblFechaHoy = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jlblFormaFarmaceutica = new javax.swing.JLabel();
        jlblMensaje = new javax.swing.JLabel();
        jtfFabricante = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblLoteDetalle = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtfCodigoFactura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtfProveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jlblPVR = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtfCodigoLote = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(0, 102, 102));
        head.setPreferredSize(new java.awt.Dimension(900, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Llenar Inventario");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        bodyCard.setLayout(new java.awt.CardLayout());

        vistaLlenar.setBackground(new java.awt.Color(255, 255, 255));
        vistaLlenar.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel40.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel40.setText("Ingrese los datos correspondientes");
        jPanel6.add(jLabel40);

        jPanel13.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblConcentracion.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jlblConcentracion.setForeground(new java.awt.Color(0, 102, 204));
        jlblConcentracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblConcentracion.setPreferredSize(new java.awt.Dimension(330, 25));
        jPanel7.add(jlblConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Código del Lote:");
        jLabel18.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 110, 25));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Fecha Registro:");
        jLabel11.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 25));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Fecha Vencimiento:");
        jLabel13.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, 25));

        jcbFechaVencimiento.setFormatoFecha("dd/MM/yyyy ");
        jcbFechaVencimiento.setPlaceholder("Desde ");
        jcbFechaVencimiento.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel7.add(jcbFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 25));

        jtfPrecioUnitarioCompra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfPrecioUnitarioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPrecioUnitarioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPrecioUnitarioCompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfPrecioUnitarioCompraKeyTyped(evt);
            }
        });
        jPanel7.add(jtfPrecioUnitarioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 50, 25));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Precio Venta Redondeado");
        jLabel16.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 190, 25));

        jtfProductoFarmaceutico.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfProductoFarmaceutico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfProductoFarmaceutico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfProductoFarmaceuticoKeyReleased(evt);
            }
        });
        jPanel7.add(jtfProductoFarmaceutico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 640, 25));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Forma Farmaceutica");
        jLabel19.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 25));

        jtfCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfCantidadKeyTyped(evt);
            }
        });
        jPanel7.add(jtfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 50, 25));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Producto Farmaceutico:");
        jLabel6.setPreferredSize(new java.awt.Dimension(330, 25));
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, -1));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Concentración");
        jLabel23.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 110, 25));

        jlblFechaHoy.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jlblFechaHoy.setForeground(new java.awt.Color(0, 102, 204));
        jlblFechaHoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblFechaHoy.setPreferredSize(new java.awt.Dimension(330, 25));
        jPanel7.add(jlblFechaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 25));

        jLabel14.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel14.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 900, 10));

        jLabel25.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel25.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 10));

        jLabel26.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Precio Unitario de Compra");
        jLabel26.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 190, 25));

        jlblFormaFarmaceutica.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jlblFormaFarmaceutica.setForeground(new java.awt.Color(0, 102, 204));
        jlblFormaFarmaceutica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblFormaFarmaceutica.setPreferredSize(new java.awt.Dimension(330, 25));
        jPanel7.add(jlblFormaFarmaceutica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 150, -1));

        jlblMensaje.setForeground(new java.awt.Color(255, 0, 0));
        jlblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMensaje.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jlblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 440, 20));

        jtfFabricante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfFabricante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfFabricanteKeyTyped(evt);
            }
        });
        jPanel7.add(jtfFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 120, 25));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("AGREGAR A LA LISTA DE LOTES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setPreferredSize(new java.awt.Dimension(452, 100));

        jtblLoteDetalle.setBorder(new javax.swing.border.MatteBorder(null));
        jtblLoteDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto"
            }
        ));
        jtblLoteDetalle.setGridColor(new java.awt.Color(0, 0, 0));
        jtblLoteDetalle.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblLoteDetalle.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jtblLoteDetalle);

        jPanel10.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jLabel29.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel10.add(jLabel29, java.awt.BorderLayout.LINE_START);

        jLabel30.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel10.add(jLabel30, java.awt.BorderLayout.LINE_END);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Lista de Lotes ");
        jLabel31.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel11.add(jLabel31);

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel3.setPreferredSize(new java.awt.Dimension(125, 25));
        jPanel12.add(jLabel3);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Còdigo Factura:");
        jPanel12.add(jLabel20);

        jtfCodigoFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfCodigoFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfCodigoFactura.setPreferredSize(new java.awt.Dimension(120, 21));
        jPanel12.add(jtfCodigoFactura);

        jLabel1.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel12.add(jLabel1);

        jLabel21.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Proveedor");
        jPanel12.add(jLabel21);

        jtfProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfProveedor.setMinimumSize(new java.awt.Dimension(100, 21));
        jtfProveedor.setPreferredSize(new java.awt.Dimension(150, 21));
        jtfProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfProveedorKeyTyped(evt);
            }
        });
        jPanel12.add(jtfProveedor);

        jLabel2.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel12.add(jLabel2);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GUARDAR LOTES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2);

        jPanel10.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 900, 190));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Fabricante:");
        jLabel15.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 80, 25));

        jlblPVR.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jlblPVR.setForeground(new java.awt.Color(0, 102, 204));
        jlblPVR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPVR.setPreferredSize(new java.awt.Dimension(330, 25));
        jPanel7.add(jlblPVR, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 50, 25));

        jLabel17.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel17.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 900, 10));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Cantidad:");
        jLabel22.setPreferredSize(new java.awt.Dimension(330, 20));
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 70, 25));

        jtfCodigoLote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtfCodigoLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel7.add(jtfCodigoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 120, 25));

        jLabel32.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLabel32.setPreferredSize(new java.awt.Dimension(700, 14));
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 900, 10));

        jPanel13.add(jPanel7, java.awt.BorderLayout.CENTER);

        vistaLlenar.add(jPanel13, java.awt.BorderLayout.CENTER);

        bodyCard.add(vistaLlenar, "card3");

        add(bodyCard, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    public void encontrarMedicamento(String objeto){        
         for (int i = 0; i < Lista_Inventario.size(); i++){
            if(jtfProductoFarmaceutico.getText().equals(Lista_Inventario.get(i).getId_Medicamento().getNombre())|| objeto.equals(Lista_Inventario.get(i).getId_Medicamento().getNombre())){                
                jlblFormaFarmaceutica.setText(Lista_Inventario.get(i).getId_Medicamento().getForma_farmaceutica());
                jlblConcentracion.setText(Lista_Inventario.get(i).getId_Medicamento().getConcentracion());
                objInventario_final=Lista_Inventario.get(i);
                MensajeProductoFarmaceutico="";                               
            break;
            }
            MensajeProductoFarmaceutico="Ingrese un Medicamento Existente";
            jlblFormaFarmaceutica.setText("");
            jlblConcentracion.setText("");  
        }        
    }      
    private void jtfProductoFarmaceuticoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProductoFarmaceuticoKeyReleased
        encontrarMedicamento("");       
    }//GEN-LAST:event_jtfProductoFarmaceuticoKeyReleased

    private void jtfPrecioUnitarioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioUnitarioCompraKeyReleased
        jlblPVR.setText(Herramienta.unDecimales(Float.parseFloat(jtfPrecioUnitarioCompra.getText())+(float)0.01));
    }//GEN-LAST:event_jtfPrecioUnitarioCompraKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Detalle_llenado objDetalle_llenado=new Detalle_llenado();
         Lote_detalle objLote_Detalle=new Lote_detalle();                
         //Lote_detalle
         //cantidad,codigo,fecha_Vencimiento,id_inventario,id_fabricante,id_factura,PVR----id_factura
         objLote_Detalle.setCantidad(Integer.parseInt(jtfCantidad.getText()));
         objLote_Detalle.setCodigo(jtfCodigoLote.getText());
         jcbFechaVencimiento.getDatoFecha().setMonth(jcbFechaVencimiento.getDatoFecha().getMonth()+1);
         objLote_Detalle.setFecha_vencimiento(jcbFechaVencimiento.getDatoFecha());
         objLote_Detalle.setInventario(objInventario_final);
         MensajeFabricante="Ingrese un Fabricante Existente";
         for (int i = 0; i < Lista_Fabricante.size(); i++){
             if(Lista_Fabricante.get(i).getNombre().equals(jtfFabricante.getText())){
                 objLote_Detalle.setFabricante(Lista_Fabricante.get(i));
                 MensajeFabricante="";
             break;
             }             
        }      
        objLote_Detalle.setPrecio_Venta_Redondeado(Float.parseFloat(jlblPVR.getText()));
        //fin Lote_detalle         
        //Detalle_Llenado
        //P.u,id_medicamento,user,fecha_registro----id_lote_detalle
        objDetalle_llenado.setPrecio_unitario(Float.parseFloat(jtfPrecioUnitarioCompra.getText()));
        objDetalle_llenado.setMedicamento(objInventario_final.getId_Medicamento());
        objDetalle_llenado.setUsuario(objPrincipal.getUsuario());
        objDetalle_llenado.setFecha_de_registro(new Date());
        objDetalle_llenado.setCantidad(Integer.parseInt(jtfCantidad.getText()));
        //objDetalle_llenado.setLote_detalle(objLote_Detalle);     
        //objInventario_final.setCantidad(objInventario_final.getCantidad()+Integer.parseInt(jtfCantidad.getText()));
        if(MensajeProductoFarmaceutico.length()==0 && MensajeFabricante.length()==0){
            Lista_Detalle_Llenado_final.add(objDetalle_llenado);
            Lista_Lote_detalle_final.add(objLote_Detalle);
            llenar_tabla_LoteDetalle(Lista_Lote_detalle_final, Lista_Detalle_Llenado_final);
            jlblMensaje.setText("");
            //limpiando campos
            jtfProductoFarmaceutico.setText("");
            jlblFormaFarmaceutica.setText("");
            jlblConcentracion.setText("");
            jtfCodigoLote.setText("");
            jtfCantidad.setText("");
            jtfPrecioUnitarioCompra.setText("");
            jlblPVR.setText("");
            jtfFabricante.setText("");
        } 
        else{
            jlblMensaje.setText(MensajeProductoFarmaceutico+" "+MensajeFabricante);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void llenar_tabla_LoteDetalle(List<Lote_detalle> listaLote,List<Detalle_llenado> listaLlenado){
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Lote","Producto Farmaceutico","Cantidad","P.U","P.V.R","Fecha Vencimiento"}; 
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {false, false,false, false,false,false};
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................          
             fila_actividad=new Object[modelo.getColumnCount()];  
             if(listaLote.size()==listaLlenado.size()){
             for (int i = 0; i < listaLote.size(); i++){
                 fila_actividad[0]=listaLote.get(i).getCodigo();
                 fila_actividad[1]=listaLote.get(i).getInventario().getId_Medicamento().getNombre();
                 fila_actividad[2]=listaLote.get(i).getCantidad();             
                 fila_actividad[3]=listaLlenado.get(i).getPrecio_unitario();
                 fila_actividad[4]=listaLote.get(i).getPrecio_Venta_Redondeado();
                 fila_actividad[5]=Herramienta.formatoFecha(listaLote.get(i).getFecha_vencimiento());         
                 modelo.addRow(fila_actividad);//agregando filas
                 }             
             }else{
                 System.out.println("error line 549 Lote:"+listaLote.size()+" Llenado"+listaLlenado.size());
             }
             
            jtblLoteDetalle.setModel(modelo); 
            jtblLoteDetalle.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblLoteDetalle.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(3).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(4).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(5).setCellRenderer(tcr);   
            jtblLoteDetalle.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblLoteDetalle.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblLoteDetalle.getTableHeader().setBackground(Color.BLUE);
            jtblLoteDetalle.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblLoteDetalle.getColumnModel().getColumn(0).setPreferredWidth(120);
            jtblLoteDetalle.getColumnModel().getColumn(1).setPreferredWidth(170);
            jtblLoteDetalle.getColumnModel().getColumn(2).setPreferredWidth(90);    
            jtblLoteDetalle.getColumnModel().getColumn(3).setPreferredWidth(90);
            jtblLoteDetalle.getColumnModel().getColumn(4).setPreferredWidth(90);
            jtblLoteDetalle.getColumnModel().getColumn(5).setPreferredWidth(150);
            ((DefaultTableCellRenderer)jtblLoteDetalle.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64                  
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Factura objFactura=new Factura();
         //factura
         Proveedor objProveedor = new Proveedor();
         //codigo_factura
         objFactura.setCodigo_factura(jtfCodigoFactura.getText());
         for (int i = 0; i < Lista_Proveedor.size(); i++){
             if(Lista_Proveedor.get(i).getNombre().equals(jtfProveedor.getText())){
                 objProveedor=Lista_Proveedor.get(i);
             }
        }
        objFactura.setProveedor(objProveedor);
        jpa.getTransaction().begin();
        for (int i = 0; i < Lista_Lote_detalle_final.size(); i++){
            Lista_Lote_detalle_final.get(i).setFactura(objFactura);            
            jpa.persist(Lista_Lote_detalle_final.get(i));            
            jpa.refresh(Lista_Lote_detalle_final.get(i));
            Lista_Detalle_Llenado_final.get(i).setLote_detalle(Lista_Lote_detalle_final.get(i));
            jpa.persist(Lista_Detalle_Llenado_final.get(i));  
            Lista_Lote_detalle_final.get(i).getInventario().agregarCantidad(Lista_Detalle_Llenado_final.get(i).getCantidad());
            jpa.persist(Lista_Lote_detalle_final.get(i).getInventario());
        }       
        jpa.getTransaction().commit();
        //nunca poner un 2persist antes de 1 refresh
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfPrecioUnitarioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrecioUnitarioCompraKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfPrecioUnitarioCompraKeyTyped

    private void jtfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCantidadKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfCantidadKeyTyped

    private void jtfFabricanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFabricanteKeyTyped
        char validar=evt.getKeyChar();
        if(!Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfFabricanteKeyTyped

    private void jtfProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProveedorKeyTyped
        char validar=evt.getKeyChar();
        if(!Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtfProveedorKeyTyped
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyCard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private rojeru_san.componentes.RSDateChooser jcbFechaVencimiento;
    private javax.swing.JLabel jlblConcentracion;
    private javax.swing.JLabel jlblFechaHoy;
    private javax.swing.JLabel jlblFormaFarmaceutica;
    private javax.swing.JLabel jlblMensaje;
    private javax.swing.JLabel jlblPVR;
    private javax.swing.JTable jtblLoteDetalle;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfCodigoFactura;
    private javax.swing.JTextField jtfCodigoLote;
    private javax.swing.JTextField jtfFabricante;
    private javax.swing.JTextField jtfPrecioUnitarioCompra;
    private javax.swing.JTextField jtfProductoFarmaceutico;
    private javax.swing.JTextField jtfProveedor;
    private javax.swing.JPanel vistaLlenar;
    // End of variables declaration//GEN-END:variables

    
    
    

}
