package com.ecoedu.Vistas.Inventario;


import com.ecoedu.Vistas.Herramienta;
import com.ecoedu.Vistas.soloMayusculas;
import com.ecoedu.Vistas.vista_base.Principal;
import com.ecoedu.model.Descruce;
import com.ecoedu.model.Detalle_llenado;
import java.awt.Color;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.ecoedu.model.Inventario;
import com.ecoedu.model.Lote_detalle;
import com.ecoedu.model.RegistroMensualLotes;
import com.ecoedu.model.Rol;
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;

import com.itextpdf.layout.property.TextAlignment;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import org.dom4j.DocumentException;
/*
1-agregar registrar un medicamento nuevo,cantidad,precio;
2-agregar cantidad a un medicamento ya existente;
3-Modificar precio Unitario de un Medicamento ya existente;
*/
public class Ver_inventario extends javax.swing.JPanel {   
    List<Inventario> Lista_Inventario=new ArrayList<>();
    List<Detalle_llenado> Lista_LotesDetalle_llenado;    
    EntityManager jpa;
    Principal objPrincipal;    
    List<Rol> Lista_Origen;
    
    public Ver_inventario(EntityManager objJPA,Principal OBJPrincipal) {
        initComponents();
        this.jpa=objJPA;
        this.objPrincipal=OBJPrincipal;
    }
    public void ConsultaBD(){
        Lista_Origen=jpa.createQuery("Select p from Rol p where id_tipo_Roles=13").getResultList();
        Query query1=jpa.createQuery("SELECT p FROM Detalle_llenado p ");
        Lista_LotesDetalle_llenado=query1.getResultList();      
    }   
    public void principalEjecucion(){
         desglozarDatos();
         jtfMedicamento.setDocument(new soloMayusculas());
        llenar_tabla_de_inventarioOperaciones(getMedicamentosParecidos(""));
        llenar_tabla_LoteDetalle(new ArrayList<Lote_detalle>());
    }
    public void desglozarDatos(){
         for (int i = 0; i < Lista_LotesDetalle_llenado.size(); i++){
            boolean auxInventario=true;
            for (int j = 0; j < Lista_Inventario.size(); j++){
                if(Lista_Inventario.get(j)==Lista_LotesDetalle_llenado.get(i).getLote_detalle().getInventario()){
                    auxInventario=false;		
                    break;
                    }
                }
            if(auxInventario){               
                Lista_Inventario.add(Lista_LotesDetalle_llenado.get(i).getLote_detalle().getInventario());
                }
            }      
}
    public List<Inventario> getMedicamentosParecidos(String palabra){
        List<Inventario> listaInventario=new ArrayList<>();
        for (int n = 0; n < Lista_Inventario.size(); n++) {
            boolean aux=true;
            for (int i = 0; i<palabra.length(); i++){               
                if(palabra.charAt(i)!=Lista_Inventario.get(n).getMedicamento().getNombre().charAt(i)){
                    aux=false;
                    break;                   
                }            
            }
            if(aux){
                listaInventario.add(Lista_Inventario.get(n));
            }
        }
        return listaInventario;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        head = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bodyCard = new javax.swing.JPanel();
        vista2 = new javax.swing.JPanel();
        headListaInventarioVoF = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblInventarioOperaciones = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jtfMedicamento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        body3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblLoteDetalle = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jlblNombreMedicamento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 204));
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(6666, 6504));
        setMinimumSize(new java.awt.Dimension(5555, 6502));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new java.awt.BorderLayout());

        head.setBackground(new java.awt.Color(0, 102, 102));
        head.setPreferredSize(new java.awt.Dimension(900, 70));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("INVENTARIO");
        jLabel12.setPreferredSize(new java.awt.Dimension(900, 70));
        head.add(jLabel12);

        add(head, java.awt.BorderLayout.PAGE_START);

        bodyCard.setLayout(new java.awt.CardLayout());

        vista2.setBackground(new java.awt.Color(255, 255, 255));

        headListaInventarioVoF.setBackground(new java.awt.Color(255, 255, 255));
        headListaInventarioVoF.setPreferredSize(new java.awt.Dimension(900, 220));
        headListaInventarioVoF.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(890, 170));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(600, 402));
        jScrollPane2.setRequestFocusEnabled(false);

        jtblInventarioOperaciones.setBorder(new javax.swing.border.MatteBorder(null));
        jtblInventarioOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto"
            }
        ));
        jtblInventarioOperaciones.setGridColor(new java.awt.Color(0, 0, 0));
        jtblInventarioOperaciones.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblInventarioOperaciones.setRequestFocusEnabled(false);
        jtblInventarioOperaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblInventarioOperacionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblInventarioOperaciones);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel22.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel8.add(jLabel22, java.awt.BorderLayout.LINE_START);

        jLabel21.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel8.add(jLabel21, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel37.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel37.setText("Nombre Medicamento");
        jPanel1.add(jLabel37);

        jtfMedicamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfMedicamento.setPreferredSize(new java.awt.Dimension(150, 30));
        jtfMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfMedicamentoKeyReleased(evt);
            }
        });
        jPanel1.add(jtfMedicamento);

        jPanel8.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Click en el Medicamento a agregar");
        jPanel8.add(jLabel15, java.awt.BorderLayout.PAGE_END);

        headListaInventarioVoF.add(jPanel8, java.awt.BorderLayout.CENTER);

        vista2.add(headListaInventarioVoF);

        body3.setBackground(new java.awt.Color(255, 255, 255));
        body3.setMaximumSize(new java.awt.Dimension(1990, 650));
        body3.setMinimumSize(new java.awt.Dimension(200, 200));
        body3.setPreferredSize(new java.awt.Dimension(900, 220));
        body3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        jtblLoteDetalle.setBorder(new javax.swing.border.MatteBorder(null));
        jtblLoteDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Producto Farmaceutico", "Cantidad", "Monto"
            }
        ));
        jtblLoteDetalle.setGridColor(new java.awt.Color(0, 0, 0));
        jtblLoteDetalle.setMinimumSize(new java.awt.Dimension(500, 100));
        jtblLoteDetalle.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jtblLoteDetalle);

        jPanel6.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jLabel23.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel6.add(jLabel23, java.awt.BorderLayout.LINE_START);

        jLabel3.setPreferredSize(new java.awt.Dimension(10, 10));
        jPanel6.add(jLabel3, java.awt.BorderLayout.LINE_END);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Lista de Lotes del Medicamento: ");
        jLabel25.setPreferredSize(new java.awt.Dimension(230, 30));
        jPanel7.add(jLabel25);

        jlblNombreMedicamento.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jlblNombreMedicamento.setForeground(new java.awt.Color(0, 102, 204));
        jlblNombreMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlblNombreMedicamento.setPreferredSize(new java.awt.Dimension(230, 30));
        jPanel7.add(jlblNombreMedicamento);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Si el medicamento no aparece es porque no le llenaron  el inventario");
        jPanel2.add(jLabel16);

        jPanel6.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        body3.add(jPanel6, java.awt.BorderLayout.CENTER);

        vista2.add(body3);

        jButton1.setText("IMPRIMIR INVENTARIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        vista2.add(jButton1);

        bodyCard.add(vista2, "card3");

        add(bodyCard, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfMedicamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfMedicamentoKeyReleased
        llenar_tabla_de_inventarioOperaciones(getMedicamentosParecidos(jtfMedicamento.getText()));
    }//GEN-LAST:event_jtfMedicamentoKeyReleased

    private void jtblInventarioOperacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblInventarioOperacionesMouseClicked
        Inventario objInventario =(Inventario)jtblInventarioOperaciones.getValueAt(jtblInventarioOperaciones.getSelectedRow(),0);
        for (Inventario inventario : Lista_Inventario){
            if(inventario==objInventario){ 
                List<Lote_detalle> auxLista_LoteDetalle=new ArrayList<>();
                for (Detalle_llenado lotedetalle : Lista_LotesDetalle_llenado){
                    if(inventario==lotedetalle.getLote_detalle().getInventario() && !lotedetalle.getLote_detalle().isIsVencido()){
                        auxLista_LoteDetalle.add(lotedetalle.getLote_detalle());
                    }                    
                }
                llenar_tabla_LoteDetalle(auxLista_LoteDetalle);
                jlblNombreMedicamento.setText(inventario.getMedicamento().getNombre());
                break;
            }        
        }
    }//GEN-LAST:event_jtblInventarioOperacionesMouseClicked
 
    public void Lista_LotesDetalle_llenado(Date Fe) throws MalformedURLException, IOException{
        
        String ol="images\\unsch.png";
        Image unsch=new Image(ImageDataFactory.create(ol));
        PdfWriter writer=null;
        try {
             writer=new PdfWriter
                ("Carpeta_de_Archivos\\Inventario_"+(Fe.getYear()+1900)+"_"+Fe.getMonth()+"_"+Fe.getDate()+".pdf");           
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(jLabel12, "El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso");
        }  
        PdfDocument pdf = new PdfDocument(writer);
        Document document=new Document(pdf,PageSize.A4.rotate());        
        PdfFont font=PdfFontFactory.createFont(FontConstants.HELVETICA);
        PdfFont bold=PdfFontFactory.createFont(FontConstants.HELVETICA_BOLD);     
        Paragraph paragIma=new Paragraph("     ").add(unsch).add("                                                   INVENTARIO  DEL MES DE "+Herramienta.getNombreMes((Fe.getMonth()+1)) ).setFontSize(16).setFont(bold);  
        document.add(paragIma); 
        Paragraph parag2=new Paragraph("Servicio Farmacia                                                                                                                                                                 "+Herramienta.formatoFechaHoraMas1(new Date()));         
        document.add(parag2);
        
        for (Rol Origen : Lista_Origen){
        boolean auxAgregar=false;
        Table table = new Table(new float[]{19,7,6,11,11,8,11,11,11,11});
        table.setWidthPercent(100);                 
        document.add(new Paragraph(" "));    
        table.addHeaderCell(new Cell().add(new Paragraph("Producto Farmacéutico").setFont(bold)).setTextAlignment(TextAlignment.CENTER));         
        table.addHeaderCell(new Cell().add(new Paragraph("Conc.").setFont(bold)).setTextAlignment(TextAlignment.CENTER));         
        table.addHeaderCell(new Cell().add(new Paragraph("F.F").setFont(bold)).setTextAlignment(TextAlignment.CENTER));        
        table.addHeaderCell(new Cell().add(new Paragraph("Lab.").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Lote").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("P.A").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Fecha Venc.").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Stock Actual").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("FACTURA").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Proveedor").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        //table.addHeaderCell(new Cell().add(new Paragraph("STOCK FINAL").setFont(bold)).setTextAlignment(TextAlignment.CENTER));              
        Collections.sort(Lista_LotesDetalle_llenado);//ordenando A-Z (método como Override)
        for (Detalle_llenado Lote_RegistroCierre : Lista_LotesDetalle_llenado){
            if(Lote_RegistroCierre.getLote_detalle().getInventario().getMedicamento().getRolorigen()==Origen){
                auxAgregar=true;
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getInventario().getMedicamento().getNombre()).setFont(font).setTextAlignment(TextAlignment.CENTER));//P.F
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getInventario().getMedicamento().getConcentracion()).setFont(font).setTextAlignment(TextAlignment.CENTER));//Conc
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getInventario().getMedicamento().getForma_farmaceutica()).setFont(font).setTextAlignment(TextAlignment.CENTER));//FF
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getRolFabricante().getNombre_rol()).setFont(font).setTextAlignment(TextAlignment.CENTER));//labo
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getCodigo()).setFont(font).setTextAlignment(TextAlignment.CENTER));//lote
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getPrecio_Venta_Redondeado()+"").setFont(font).setTextAlignment(TextAlignment.CENTER));//P.A
            if(Lote_RegistroCierre.getLote_detalle().getFecha_vencimiento().getTime()-(new Date()).getTime()>=0){
                if((Lote_RegistroCierre.getLote_detalle().getFecha_vencimiento().getTime()-(new Date()).getTime())/86400000 <=6*30){
                    table.addCell(new Paragraph(Herramienta.formatoFecha(Lote_RegistroCierre.getLote_detalle().getFecha_vencimiento())).setFont(font).setTextAlignment(TextAlignment.CENTER).setBackgroundColor(com.itextpdf.kernel.color.Color.YELLOW));
                    }
                else{
                    table.addCell(new Paragraph(Herramienta.formatoFecha(Lote_RegistroCierre.getLote_detalle().getFecha_vencimiento())).setFont(font).setTextAlignment(TextAlignment.CENTER).setBackgroundColor(com.itextpdf.kernel.color.Color.WHITE));
                    }
            }
            else{
                table.addCell(new Paragraph(Herramienta.formatoFecha(Lote_RegistroCierre.getLote_detalle().getFecha_vencimiento())).setFont(font).setTextAlignment(TextAlignment.CENTER).setBackgroundColor(com.itextpdf.kernel.color.Color.RED));
                }
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getCantidad()+"").setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getFactura().getCodigo_factura()).setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
            table.addCell(new Paragraph(Lote_RegistroCierre.getLote_detalle().getRolFabricante().getNombre_rol()).setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
            //table.addCell(new Paragraph(Integer.toString(Lote_RegistroCierre.getLote_detalle().getCantidad())).setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
        }}
        if(auxAgregar){document.add(new Paragraph(Origen.getNombre_rol()).setTextAlignment(TextAlignment.CENTER));document.add(table);}
        }
        document.close();          
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        try {
            Date Fe=new Date();
            Lista_LotesDetalle_llenado(Fe);
            String url="Carpeta_de_Archivos\\Inventario_"+(Fe.getYear()+1900)+"_"+Fe.getMonth()+"_"+Fe.getDate()+".pdf";
            ProcessBuilder p=new ProcessBuilder();
            p.command("cmd.exe","/c",url);
            p.start();                          
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(jtfMedicamento, ex.toString());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(jtfMedicamento, ex.toString());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void imprimir(Date Fe) throws FileNotFoundException, DocumentException, IOException{
        Detalle_llenado objDetalleLlenado_AñoActual=null;
        String ol="images\\unsch.png";
        Image unsch=new Image(ImageDataFactory.create(ol));
        PdfWriter writer=null;
        try {
             writer=new PdfWriter
                ("Carpeta_de_Archivos\\Inventario_"+(Fe.getYear()+1900)+"_"+Fe.getMonth()+"_"+Fe.getDate()+".pdf");           
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(jLabel12, "El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso");
        }  
        PdfDocument pdf = new PdfDocument(writer);
        Document document=new Document(pdf,PageSize.A4.rotate());        
        PdfFont font=PdfFontFactory.createFont(FontConstants.HELVETICA);
        PdfFont bold=PdfFontFactory.createFont(FontConstants.HELVETICA_BOLD);     
        Table table = new Table(new float[]{18,6,5,10,10,7,10,10,10,10,9});
        table.setWidthPercent(100);
        //Paragraph parag=new Paragraph("KARDEX DIARIO MEDICAMENTOS").setFontSize(16).setFont(bold);
        Paragraph paragIma=new Paragraph("     ").add(unsch).add("                                                          KARDEX MEDICAMENTOS").setFontSize(16).setFont(bold);  
   
        document.add(paragIma);

        Paragraph parag=new Paragraph("SEMESTRE 2019-II").setTextAlignment(TextAlignment.CENTER);
        document.add(parag);      
        Paragraph parag2=new Paragraph("Servicio Farmacia                                                                                                                                                "+Herramienta.formatoFechaHoraMas1(new Date()));         
        document.add(parag2);
        document.add(new Paragraph(" "));    
        table.addHeaderCell(new Cell().add(new Paragraph("Producto Farmacéutico").setFont(bold)).setTextAlignment(TextAlignment.CENTER));         
        table.addHeaderCell(new Cell().add(new Paragraph("Conc.").setFont(bold)).setTextAlignment(TextAlignment.CENTER));         
        table.addHeaderCell(new Cell().add(new Paragraph("F.F").setFont(bold)).setTextAlignment(TextAlignment.CENTER));        
        table.addHeaderCell(new Cell().add(new Paragraph("Lab.").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Lote").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("P.A").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Fecha Venc.").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Stock Inicial").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("FACTURA").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("Proveedor").setFont(bold)).setTextAlignment(TextAlignment.CENTER)); 
        table.addHeaderCell(new Cell().add(new Paragraph("STOCK FINAL").setFont(bold)).setTextAlignment(TextAlignment.CENTER));              
      Collections.sort(Lista_LotesDetalle_llenado);//ordenando A-Z (método como Override)
        for (Detalle_llenado Lote_detalle : Lista_LotesDetalle_llenado){
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getInventario().getMedicamento().getNombre()).setFont(font).setTextAlignment(TextAlignment.CENTER));//P.F
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getInventario().getMedicamento().getConcentracion()).setFont(font).setTextAlignment(TextAlignment.CENTER));//Conc
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getInventario().getMedicamento().getForma_farmaceutica()).setFont(font).setTextAlignment(TextAlignment.CENTER));//FF
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getRolFabricante().getNombre_rol()).setFont(font).setTextAlignment(TextAlignment.CENTER));//labo
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getCodigo()).setFont(font).setTextAlignment(TextAlignment.CENTER));//lote
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getPrecio_Venta_Redondeado()+"").setFont(font).setTextAlignment(TextAlignment.CENTER));//P.A
            if(Lote_detalle.getLote_detalle().getFecha_vencimiento().getTime()-(new Date()).getTime()>=0){
                if((Lote_detalle.getLote_detalle().getFecha_vencimiento().getTime()-(new Date()).getTime())/86400000 <=6*30){
                    System.out.println("volar");
                    table.addCell(new Paragraph(Herramienta.formatoFecha(Lote_detalle.getLote_detalle().getFecha_vencimiento())).setFont(font).setTextAlignment(TextAlignment.CENTER).setBackgroundColor(com.itextpdf.kernel.color.Color.YELLOW));
                    }
                else{
                    table.addCell(new Paragraph(Herramienta.formatoFecha(Lote_detalle.getLote_detalle().getFecha_vencimiento())).setFont(font).setTextAlignment(TextAlignment.CENTER).setBackgroundColor(com.itextpdf.kernel.color.Color.WHITE));
                    }
            }
            else{
                table.addCell(new Paragraph(Herramienta.formatoFecha(Lote_detalle.getLote_detalle().getFecha_vencimiento())).setFont(font).setTextAlignment(TextAlignment.CENTER).setBackgroundColor(com.itextpdf.kernel.color.Color.RED));
                }
            table.addCell(new Paragraph(Integer.toString(Lote_detalle.getCantidad())).setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getFactura().getCodigo_factura()).setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
            table.addCell(new Paragraph(Lote_detalle.getLote_detalle().getRolFabricante().getNombre_rol()).setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
            table.addCell(new Paragraph(Integer.toString(Lote_detalle.getLote_detalle().getCantidad())).setFont(font).setTextAlignment(TextAlignment.CENTER));//stock final
    
        }     
        document.add(table);        
        document.close();              
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body3;
    private javax.swing.JPanel bodyCard;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel head;
    private javax.swing.JPanel headListaInventarioVoF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jlblNombreMedicamento;
    private javax.swing.JTable jtblInventarioOperaciones;
    private javax.swing.JTable jtblLoteDetalle;
    private javax.swing.JTextField jtfMedicamento;
    private javax.swing.JPanel vista2;
    // End of variables declaration//GEN-END:variables

     public void llenar_tabla_LoteDetalle(List<Lote_detalle> listaLote){
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Código Lote","Cantidad","P.V.R","Fecha de Vencimiento"}; 
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {false, false,false, false};
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................          
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < listaLote.size(); i++){
                 fila_actividad[0]=listaLote.get(i).getCodigo();
                 fila_actividad[1]=listaLote.get(i).getCantidad();             
                 fila_actividad[2]=listaLote.get(i).getPrecio_Venta_Redondeado();
                 fila_actividad[3]=Herramienta.formatoFecha(listaLote.get(i).getFecha_vencimiento());             
                 modelo.addRow(fila_actividad);//agregando filas
                 }
             
            jtblLoteDetalle.setModel(modelo); 
            jtblLoteDetalle.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblLoteDetalle.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(1).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(2).setCellRenderer(tcr);
            jtblLoteDetalle.getColumnModel().getColumn(3).setCellRenderer(tcr);
   
            jtblLoteDetalle.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblLoteDetalle.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblLoteDetalle.getTableHeader().setBackground(Color.BLUE);
            jtblLoteDetalle.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblLoteDetalle.getColumnModel().getColumn(0).setPreferredWidth(154);
            jtblLoteDetalle.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtblLoteDetalle.getColumnModel().getColumn(2).setPreferredWidth(100);    
            jtblLoteDetalle.getColumnModel().getColumn(3).setPreferredWidth(100);
            ((DefaultTableCellRenderer)jtblLoteDetalle.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64                  
    }
   
    public void llenar_tabla_de_inventarioOperaciones(List<Inventario> listaInventario){
        DefaultTableModel modelo;
        Object[] fila_actividad;
             //.....................................TABLA......................................
             String [] lista={"Producto Farmacéutico","Cantidad"}; 
             modelo=new DefaultTableModel(null,lista){
                 boolean[] canEdit = new boolean [] {
                       false, false
                         };
                 public boolean isCellEditable(int rowIndex, int columnIndex) {
                     return canEdit [columnIndex];
                     }
                 };
             //.....................................TABLA...........Fin......................
            
             fila_actividad=new Object[modelo.getColumnCount()];  
             for (int i = 0; i < listaInventario.size(); i++){
                 fila_actividad[0]=listaInventario.get(i);             
                 fila_actividad[1]=listaInventario.get(i).getCantidad();                  
                 modelo.addRow(fila_actividad);//agregando filas
                 }
             
            jtblInventarioOperaciones.setModel(modelo); 
            jtblInventarioOperaciones.setGridColor(Color.black);
            //jTable1.setBackground(Color.red);
            //jTable1.setForeground(Color.blue);
            DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
            tcr.setHorizontalAlignment(SwingConstants.CENTER);
            jtblInventarioOperaciones.getColumnModel().getColumn(0).setCellRenderer(tcr);
            jtblInventarioOperaciones.getColumnModel().getColumn(1).setCellRenderer(tcr);       
   
            jtblInventarioOperaciones.setFont(new java.awt.Font("Tahoma", 0, 15));
            jtblInventarioOperaciones.getTableHeader().setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 20));
            jtblInventarioOperaciones.getTableHeader().setBackground(Color.BLUE);
            jtblInventarioOperaciones.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 30));
            jtblInventarioOperaciones.getColumnModel().getColumn(0).setPreferredWidth(200);
            jtblInventarioOperaciones.getColumnModel().getColumn(1).setPreferredWidth(150);
                   
            ((DefaultTableCellRenderer)jtblInventarioOperaciones.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            //864-550=64                  
    }
    
    
    

}
